# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.runs/BD_core_0_synth_1/BD_core_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "BD_core_0_synth_1" START { ROLLUP_AUTO }
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/mref
create_project -in_memory -part xczu3eg-sbva484-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.cache/wt [current_project]
set_property parent.project_path /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part avnet-tria:ultra96v2:part0:1.3 [current_project]
update_ip_catalog
set_property ip_output_repo /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AMOALU.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4Buffer.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4Deinterleaver.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4IdIndexer.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4IdIndexer_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4UserYanker.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4UserYanker_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Arbiter2_Valid_PTWReq.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Arbiter3_LLWB.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetRegVec_w1_i0.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetRegVec_w1_i1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetRegVec_w2_i0.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BTB.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BankBinder.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BootROMClockSinkDomain.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BreakpointUnit.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BroadcastFilter.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BundleBridgeNexus_UInt1_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CLINT.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CLINTClockSinkDomain.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CSRFile.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ChipTop.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ChipyardPRCICtrlClockSinkDomain.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ClockGroupAggregator_allClocks.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ClockGroupCombiner.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ClockGroupResetSynchronizer.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CoherenceManagerWrapper.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CompareRecFN.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DCache.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DCacheDataArray.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DigitalTop.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRawFN_small_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRawFN_small_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFMToRaw_small_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFMToRaw_small_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFM_small_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFM_small_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ErrorDeviceWrapper.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPToFP.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPToInt.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPU.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPUDecoder.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPUFMAPipe_l3_f16.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPUFMAPipe_l3_f32.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FixedClockBroadcast_3.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FixedClockBroadcast_5.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Frontend.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/GenericDigitalInIOCell.v
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/GenericDigitalOutIOCell.v
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/HellaCacheArbiter.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IBuf.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ICache.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/INToRecFN_i32_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/INToRecFN_i32_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ITLB.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncCrossingSource_n1x1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncCrossingSource_n1x2.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncSyncCrossingSink_n1x1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncSyncCrossingSink_n1x2.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntToFP.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntXbar_i4_o1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MaxPeriodFibonacciLFSR.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MemoryBus.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNPipe_l2_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNPipe_l2_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_postMul_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_postMul_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_preMul_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_preMul_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulDiv.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/OptimizationBarrier_PTE.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/OptimizationBarrier_TLBEntryData.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/OptimizationBarrier_UInt.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PLICClockSinkDomain.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PMAChecker.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PMPChecker_s2.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PTW.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PeripheryBus_cbus.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PeripheryBus_pbus.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PlusArgTimeout.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ProbePicker.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_AXI4BundleARW.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_AXI4BundleARW_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_AXI4BundleW.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_BundleMap.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_BundleMap_6.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_RegMapperInput_i23_m8.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_TLBundleA_a14d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleAR.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleAW.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleB.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleR.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleW.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a13d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a14d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a21d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a28d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a28d64s4k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleB_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleC_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a13d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a14d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a21d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a28d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a28d64s4k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleE_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue8_AXI4BundleR.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue8_TLBroadcastData.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RVCExpander.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RecFNToIN_e8_s24_i32.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RecFNToRecFN.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a13d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a17d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a21d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a26d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a28d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a28d64s4k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ResetCatchAndSync_d3.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Rocket.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RocketALU.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RocketTile.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie5_is13_oe5_os11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie6_is32_oe5_os11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie6_is32_oe8_os24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie8_is24_oe5_os11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie8_is26_oe8_os24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundRawFNToRecFN_e5_s11.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundRawFNToRecFN_e8_s24.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ScratchpadBank.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ShiftQueue.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SystemBus.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLAtomicAutomata_cbus.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLAtomicAutomata_pbus.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBroadcast.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBroadcastTracker.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBroadcastTracker_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBroadcastTracker_2.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBroadcastTracker_3.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a13d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a14d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a21d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a28d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a28d64s4k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a32d64s2k2z4c_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLError.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_BootAddrReg.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_BootROM.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_CLINT.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_PLIC.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_ScratchpadBank.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_TileClockGater.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_TileResetSetter.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_bootrom.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_clint.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_plic.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_prci_ctrl.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_mbus_to_memory_controller_port_named_axi4.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_pbus_to_bootaddressreg.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_sbus_to_port_named_mmio_port_axi4.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLPLIC.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLRAM_ScratchpadBank.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLROM.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLToAXI4.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLToAXI4_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_MasterXbar_RocketTile_i2_o1_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_cbus_in_i2_o1_a28d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_cbus_out_i1_o6_a28d64s3k1z4u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_mbus_i1_o2_a31d64s4k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_prcibus_i1_o2_a21d64s3k1z3u.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_sbus_i1_o3_a32d64s2k2z4c.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TileClockGater.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TilePRCIDomain.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TileResetSetter.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/mem.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/plusarg_reader.v
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x100.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x102.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x108.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x114.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x117.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x40.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x6.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x61.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x71.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x73.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x78.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x79.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x98.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_8x72.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_8x77.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_sink_2x2.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/regfile_32x33.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rf_31x32.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_dcache_data_arrays_0.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_dcache_data_arrays_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_dcache_tag_array.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_icache_data_arrays_0.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_icache_data_arrays_1.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_icache_tag_array.sv
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/table_512x1.sv
}
read_verilog -library xil_defaultlib {
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/chipyard.harness.TestHarness.RV32RocketFPGAConfig.top.mems.v
  /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RV32RocketCoreTop.v
}
read_ip -quiet /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.srcs/sources_1/bd/BD/ip/BD_core_0/BD_core_0.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top BD_core_0 -part xczu3eg-sbva484-1-i -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all BD_core_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BD_core_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file BD_core_0_utilization_synth.rpt -pb BD_core_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.runs/BD_core_0_synth_1/BD_core_0.dcp /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.ip_user_files/ip/BD_core_0]} {
  catch { 
    file copy -force /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_stub.v /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.ip_user_files/ip/BD_core_0
  }
}

if {[file isdir /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.ip_user_files/ip/BD_core_0]} {
  catch { 
    file copy -force /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_stub.vhdl /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.ip_user_files/ip/BD_core_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "BD_core_0_synth_1" END { }
