-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
-- Date        : Sat Feb  8 00:04:21 2025
-- Host        : hakam-MS-7D46 running 64-bit Ubuntu 24.04.1 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/ip/BD_core_0/BD_core_0_stub.vhdl
-- Design      : BD_core_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu3eg-sbva484-1-i
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity BD_core_0 is
  Port ( 
    M_AXI_MMIO_ACLK : out STD_LOGIC;
    M_AXI_MMIO_AWREADY : in STD_LOGIC;
    M_AXI_MMIO_AWVALID : out STD_LOGIC;
    M_AXI_MMIO_AWID : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M_AXI_MMIO_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_MMIO_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MMIO_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MMIO_AWLOCK : out STD_LOGIC;
    M_AXI_MMIO_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MMIO_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_WREADY : in STD_LOGIC;
    M_AXI_MMIO_WVALID : out STD_LOGIC;
    M_AXI_MMIO_WDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    M_AXI_MMIO_WSTRB : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_MMIO_WLAST : out STD_LOGIC;
    M_AXI_MMIO_BREADY : out STD_LOGIC;
    M_AXI_MMIO_BVALID : in STD_LOGIC;
    M_AXI_MMIO_BID : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MMIO_ARREADY : in STD_LOGIC;
    M_AXI_MMIO_ARVALID : out STD_LOGIC;
    M_AXI_MMIO_ARID : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M_AXI_MMIO_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_MMIO_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MMIO_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MMIO_ARLOCK : out STD_LOGIC;
    M_AXI_MMIO_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MMIO_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_RREADY : out STD_LOGIC;
    M_AXI_MMIO_RVALID : in STD_LOGIC;
    M_AXI_MMIO_RID : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MMIO_RDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    M_AXI_MMIO_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MMIO_RLAST : in STD_LOGIC;
    M_AXI_MEM_ACLK : out STD_LOGIC;
    M_AXI_MEM_AWREADY : in STD_LOGIC;
    M_AXI_MEM_AWVALID : out STD_LOGIC;
    M_AXI_MEM_AWID : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M_AXI_MEM_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_MEM_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MEM_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MEM_AWLOCK : out STD_LOGIC;
    M_AXI_MEM_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MEM_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_WREADY : in STD_LOGIC;
    M_AXI_MEM_WVALID : out STD_LOGIC;
    M_AXI_MEM_WDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    M_AXI_MEM_WSTRB : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_MEM_WLAST : out STD_LOGIC;
    M_AXI_MEM_BREADY : out STD_LOGIC;
    M_AXI_MEM_BVALID : in STD_LOGIC;
    M_AXI_MEM_BID : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MEM_ARREADY : in STD_LOGIC;
    M_AXI_MEM_ARVALID : out STD_LOGIC;
    M_AXI_MEM_ARID : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    M_AXI_MEM_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    M_AXI_MEM_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MEM_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MEM_ARLOCK : out STD_LOGIC;
    M_AXI_MEM_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    M_AXI_MEM_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_RREADY : out STD_LOGIC;
    M_AXI_MEM_RVALID : in STD_LOGIC;
    M_AXI_MEM_RID : in STD_LOGIC_VECTOR ( 3 downto 0 );
    M_AXI_MEM_RDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    M_AXI_MEM_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    M_AXI_MEM_RLAST : in STD_LOGIC;
    custom_boot : in STD_LOGIC;
    reset_io : in STD_LOGIC;
    clock_uncore : in STD_LOGIC;
    clock_tap : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of BD_core_0 : entity is "BD_core_0,RV32RocketCoreTop,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of BD_core_0 : entity is "BD_core_0,RV32RocketCoreTop,{x_ipProduct=Vivado 2024.2,x_ipVendor=xilinx.com,x_ipLibrary=module_ref,x_ipName=RV32RocketCoreTop,x_ipVersion=1.0,x_ipCoreRevision=1,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of BD_core_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of BD_core_0 : entity is "module_ref";
end BD_core_0;

architecture stub of BD_core_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "M_AXI_MMIO_ACLK,M_AXI_MMIO_AWREADY,M_AXI_MMIO_AWVALID,M_AXI_MMIO_AWID[3:0],M_AXI_MMIO_AWADDR[31:0],M_AXI_MMIO_AWLEN[7:0],M_AXI_MMIO_AWSIZE[2:0],M_AXI_MMIO_AWBURST[1:0],M_AXI_MMIO_AWLOCK,M_AXI_MMIO_AWCACHE[3:0],M_AXI_MMIO_AWPROT[2:0],M_AXI_MMIO_AWQOS[3:0],M_AXI_MMIO_WREADY,M_AXI_MMIO_WVALID,M_AXI_MMIO_WDATA[63:0],M_AXI_MMIO_WSTRB[7:0],M_AXI_MMIO_WLAST,M_AXI_MMIO_BREADY,M_AXI_MMIO_BVALID,M_AXI_MMIO_BID[3:0],M_AXI_MMIO_BRESP[1:0],M_AXI_MMIO_ARREADY,M_AXI_MMIO_ARVALID,M_AXI_MMIO_ARID[3:0],M_AXI_MMIO_ARADDR[31:0],M_AXI_MMIO_ARLEN[7:0],M_AXI_MMIO_ARSIZE[2:0],M_AXI_MMIO_ARBURST[1:0],M_AXI_MMIO_ARLOCK,M_AXI_MMIO_ARCACHE[3:0],M_AXI_MMIO_ARPROT[2:0],M_AXI_MMIO_ARQOS[3:0],M_AXI_MMIO_RREADY,M_AXI_MMIO_RVALID,M_AXI_MMIO_RID[3:0],M_AXI_MMIO_RDATA[63:0],M_AXI_MMIO_RRESP[1:0],M_AXI_MMIO_RLAST,M_AXI_MEM_ACLK,M_AXI_MEM_AWREADY,M_AXI_MEM_AWVALID,M_AXI_MEM_AWID[3:0],M_AXI_MEM_AWADDR[31:0],M_AXI_MEM_AWLEN[7:0],M_AXI_MEM_AWSIZE[2:0],M_AXI_MEM_AWBURST[1:0],M_AXI_MEM_AWLOCK,M_AXI_MEM_AWCACHE[3:0],M_AXI_MEM_AWPROT[2:0],M_AXI_MEM_AWQOS[3:0],M_AXI_MEM_WREADY,M_AXI_MEM_WVALID,M_AXI_MEM_WDATA[63:0],M_AXI_MEM_WSTRB[7:0],M_AXI_MEM_WLAST,M_AXI_MEM_BREADY,M_AXI_MEM_BVALID,M_AXI_MEM_BID[3:0],M_AXI_MEM_BRESP[1:0],M_AXI_MEM_ARREADY,M_AXI_MEM_ARVALID,M_AXI_MEM_ARID[3:0],M_AXI_MEM_ARADDR[31:0],M_AXI_MEM_ARLEN[7:0],M_AXI_MEM_ARSIZE[2:0],M_AXI_MEM_ARBURST[1:0],M_AXI_MEM_ARLOCK,M_AXI_MEM_ARCACHE[3:0],M_AXI_MEM_ARPROT[2:0],M_AXI_MEM_ARQOS[3:0],M_AXI_MEM_RREADY,M_AXI_MEM_RVALID,M_AXI_MEM_RID[3:0],M_AXI_MEM_RDATA[63:0],M_AXI_MEM_RRESP[1:0],M_AXI_MEM_RLAST,custom_boot,reset_io,clock_uncore,clock_tap";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ACLK : signal is "xilinx.com:signal:clock:1.0 M_AXI_MMIO_ACLK CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of M_AXI_MMIO_ACLK : signal is "master";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of M_AXI_MMIO_ACLK : signal is "XIL_INTERFACENAME M_AXI_MMIO_ACLK, ASSOCIATED_BUSIF M_AXI_MMIO, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN BD_core_0_M_AXI_MMIO_ACLK, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWREADY";
  attribute X_INTERFACE_MODE of M_AXI_MMIO_AWREADY : signal is "master";
  attribute X_INTERFACE_PARAMETER of M_AXI_MMIO_AWREADY : signal is "XIL_INTERFACENAME M_AXI_MMIO, DATA_WIDTH 64, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN BD_core_0_M_AXI_MMIO_ACLK, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWVALID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWADDR : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWADDR";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWLEN : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWLEN";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWSIZE";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWBURST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWBURST";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWLOCK";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWCACHE";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWPROT : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWPROT";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_AWQOS : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO AWQOS";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_WREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO WREADY";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_WVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO WVALID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_WDATA : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO WDATA";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_WSTRB : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO WSTRB";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_WLAST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO WLAST";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_BREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO BREADY";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_BVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO BVALID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_BID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO BID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_BRESP : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO BRESP";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARREADY";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARVALID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARADDR : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARADDR";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARLEN : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARLEN";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARSIZE";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARBURST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARBURST";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARLOCK";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARCACHE";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARPROT : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARPROT";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_ARQOS : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO ARQOS";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_RREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO RREADY";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_RVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO RVALID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_RID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO RID";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_RDATA : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO RDATA";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_RRESP : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO RRESP";
  attribute X_INTERFACE_INFO of M_AXI_MMIO_RLAST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MMIO RLAST";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ACLK : signal is "xilinx.com:signal:clock:1.0 M_AXI_MEM_ACLK CLK";
  attribute X_INTERFACE_MODE of M_AXI_MEM_ACLK : signal is "master";
  attribute X_INTERFACE_PARAMETER of M_AXI_MEM_ACLK : signal is "XIL_INTERFACENAME M_AXI_MEM_ACLK, ASSOCIATED_BUSIF M_AXI_MEM, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN BD_core_0_M_AXI_MEM_ACLK, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWREADY";
  attribute X_INTERFACE_MODE of M_AXI_MEM_AWREADY : signal is "master";
  attribute X_INTERFACE_PARAMETER of M_AXI_MEM_AWREADY : signal is "XIL_INTERFACENAME M_AXI_MEM, DATA_WIDTH 64, PROTOCOL AXI4, FREQ_HZ 100000000, ID_WIDTH 4, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN BD_core_0_M_AXI_MEM_ACLK, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWVALID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWADDR : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWADDR";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWLEN : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWLEN";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWSIZE";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWBURST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWBURST";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWLOCK";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWCACHE";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWPROT : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWPROT";
  attribute X_INTERFACE_INFO of M_AXI_MEM_AWQOS : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM AWQOS";
  attribute X_INTERFACE_INFO of M_AXI_MEM_WREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM WREADY";
  attribute X_INTERFACE_INFO of M_AXI_MEM_WVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM WVALID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_WDATA : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM WDATA";
  attribute X_INTERFACE_INFO of M_AXI_MEM_WSTRB : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM WSTRB";
  attribute X_INTERFACE_INFO of M_AXI_MEM_WLAST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM WLAST";
  attribute X_INTERFACE_INFO of M_AXI_MEM_BREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM BREADY";
  attribute X_INTERFACE_INFO of M_AXI_MEM_BVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM BVALID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_BID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM BID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_BRESP : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM BRESP";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARREADY";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARVALID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARADDR : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARADDR";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARLEN : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARLEN";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARSIZE";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARBURST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARBURST";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARLOCK";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARCACHE";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARPROT : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARPROT";
  attribute X_INTERFACE_INFO of M_AXI_MEM_ARQOS : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM ARQOS";
  attribute X_INTERFACE_INFO of M_AXI_MEM_RREADY : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM RREADY";
  attribute X_INTERFACE_INFO of M_AXI_MEM_RVALID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM RVALID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_RID : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM RID";
  attribute X_INTERFACE_INFO of M_AXI_MEM_RDATA : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM RDATA";
  attribute X_INTERFACE_INFO of M_AXI_MEM_RRESP : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM RRESP";
  attribute X_INTERFACE_INFO of M_AXI_MEM_RLAST : signal is "xilinx.com:interface:aximm:1.0 M_AXI_MEM RLAST";
  attribute X_INTERFACE_INFO of reset_io : signal is "xilinx.com:signal:reset:1.0 reset_io RST";
  attribute X_INTERFACE_MODE of reset_io : signal is "slave";
  attribute X_INTERFACE_PARAMETER of reset_io : signal is "XIL_INTERFACENAME reset_io, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of clock_uncore : signal is "xilinx.com:signal:clock:1.0 clock_uncore CLK";
  attribute X_INTERFACE_MODE of clock_uncore : signal is "slave";
  attribute X_INTERFACE_PARAMETER of clock_uncore : signal is "XIL_INTERFACENAME clock_uncore, FREQ_HZ 99999001, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN BD_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of clock_tap : signal is "xilinx.com:signal:clock:1.0 clock_tap CLK";
  attribute X_INTERFACE_MODE of clock_tap : signal is "master";
  attribute X_INTERFACE_PARAMETER of clock_tap : signal is "XIL_INTERFACENAME clock_tap, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN BD_core_0_clock_tap, INSERT_VIP 0";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "RV32RocketCoreTop,Vivado 2024.2";
begin
end;
