# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/constraints/constraints.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_zynq_ultra_ps_e_0_0/BD_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BD_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_core_0/BD_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_core_0 || ORIG_REF_NAME==BD_core_0} -quiet] -quiet

# XDC: /home/hakam/Repos/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32Rocket/RV32Rocket.gen/sources_1/bd/BD/BD_ooc.xdc
