# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-91027-Desktop-Home/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu3eg-sbva484-1-i
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AMOALU.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4Buffer.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4Deinterleaver.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4IdIndexer.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4IdIndexer_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4UserYanker.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AXI4UserYanker_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Arbiter2_Valid_PTWReq.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Arbiter3_LLWB.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetRegVec_w1_i0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetRegVec_w1_i1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetRegVec_w2_i0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Atomics.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BTB.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BankBinder.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BankedStore.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BootROMClockSinkDomain.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BreakpointUnit.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/BundleBridgeNexus_UInt1_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CLINT.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CLINTClockSinkDomain.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CSRFile.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ChipTop.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ChipyardPRCICtrlClockSinkDomain.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ClockGroupAggregator_allClocks.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ClockGroupCombiner.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ClockGroupResetSynchronizer.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CoherenceManagerWrapper.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/CompareRecFN.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DCache.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DCacheDataArray.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DigitalTop.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Directory.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRawFN_small_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRawFN_small_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFMToRaw_small_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFMToRaw_small_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFM_small_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/DivSqrtRecFM_small_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ErrorDeviceWrapper.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPToFP.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPToInt.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPU.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPUDecoder.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPUFMAPipe_l3_f16.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FPUFMAPipe_l3_f32.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FixedClockBroadcast_3.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/FixedClockBroadcast_5.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Frontend.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/GenericDigitalInIOCell.v
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/GenericDigitalOutIOCell.v
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/HellaCacheArbiter.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IBuf.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ICache.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IDPool.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/INToRecFN_i32_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/INToRecFN_i32_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ITLB.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/InclusiveCache.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/InclusiveCacheBankScheduler.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/InclusiveCacheControl.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncCrossingSource_n1x1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncCrossingSource_n1x2.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncSyncCrossingSink_n1x1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntSyncSyncCrossingSink_n1x2.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntToFP.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/IntXbar_i4_o1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ListBuffer_PutBufferAEntry_q40_e40.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ListBuffer_PutBufferCEntry_q2_e16.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ListBuffer_QueuedRequest_q21_e33.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MSHR.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MaxPeriodFibonacciLFSR.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MemoryBus.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNPipe_l2_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNPipe_l2_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_postMul_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_postMul_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_preMul_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulAddRecFNToRaw_preMul_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/MulDiv.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/OptimizationBarrier_PTE.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/OptimizationBarrier_TLBEntryData.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/OptimizationBarrier_UInt.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PLICClockSinkDomain.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PMAChecker.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PMPChecker_s2.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PTW.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PeripheryBus_cbus.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PeripheryBus_pbus.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/PlusArgTimeout.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ProbePicker.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue12_TLBundleC_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_AXI4BundleARW.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_AXI4BundleARW_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_AXI4BundleW.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_BankedStoreInnerAddress.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_BundleMap.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_BundleMap_8.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_DirectoryWrite.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_RegMapperInput_i23_m8.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_RegMapperInput_i9_m8.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_SinkXRequest.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_SourceXRequest.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_TLBundleA_a14d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_TLBundleA_a26d64s8k1z2u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_TLBundleA_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_TLBundleD_a26d64s8k1z2u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue1_TLBundleD_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleAR.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleAW.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleB.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleR.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_AXI4BundleW.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a13d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a14d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a21d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a28d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a28d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a31d64s1k3z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a31d64s2k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleA_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleB_a31d64s2k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleC_a31d64s2k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleC_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a13d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a14d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a21d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a28d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a28d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a31d64s1k3z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a31d64s2k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleD_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleE_a31d64s2k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue2_TLBundleE_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue3_BankedStoreInnerDecoded.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue8_AXI4BundleR.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Queue8_UInt8.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RVCExpander.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RecFNToIN_e8_s24_i32.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RecFNToRecFN.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a13d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a17d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a21d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a26d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Repeater_TLBundleA_a28d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ResetCatchAndSync_d3.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/Rocket.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RocketALU.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RocketTile.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie5_is13_oe5_os11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie6_is32_oe5_os11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie6_is32_oe8_os24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie8_is24_oe5_os11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundAnyRawFNToRecFN_ie8_is26_oe8_os24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundRawFNToRecFN_e5_s11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RoundRawFNToRecFN_e8_s24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ScratchpadBank.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SerialWidthAdapter.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SerialWidthAggregator.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SerialWidthSlicer.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ShiftQueue.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SinkA.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SinkC.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SinkD.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SinkE.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SinkX.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SourceA.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SourceB.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SourceC.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SourceD.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SourceE.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SourceX.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/SystemBus.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLAtomicAutomata_cbus.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLAtomicAutomata_pbus.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a13d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a13d64s4k1z3u_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a14d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a21d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a26d64s8k1z2u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a28d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a28d64s4k1z3u_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a28d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a31d64s1k3z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a31d64s2k3z4c_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLBuffer_a31d64s3k3z3c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLCacheCork.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLError.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_BootAddrReg.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_BootROM.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_CLINT.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_LLCCtrl.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_PLIC.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_ScratchpadBank.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_TileClockGater.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLFragmenter_TileResetSetter.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_bootrom.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_clint.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_l2_ctrl.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_plic.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_cbus_to_prci_ctrl.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_mbus_to_memory_controller_port_named_axi4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_pbus_to_bootaddressreg.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLInterconnectCoupler_sbus_to_port_named_mmio_port_axi4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_10.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_11.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_12.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_13.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_14.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_15.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_16.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_17.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_18.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_19.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_2.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_20.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_21.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_22.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_23.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_24.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_25.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_26.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_27.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_28.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_29.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_3.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_30.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_31.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_32.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_33.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_34.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_35.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_36.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_37.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_38.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_39.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_40.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_41.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_42.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_43.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_44.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_45.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_5.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_7.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_8.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLMonitor_9.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLPLIC.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLRAM_ScratchpadBank.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLROM.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLToAXI4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLToAXI4_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_MasterXbar_RocketTile_i2_o1_a31d64s2k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_cbus_in_i2_o1_a28d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_cbus_out_i1_o7_a28d64s4k1z4u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_mbus_i1_o2_a31d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_prcibus_i1_o2_a21d64s4k1z3u.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TLXbar_sbus_i2_o3_a31d64s3k3z4c.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TSIToTileLink.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TileClockGater.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TilePRCIDomain.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/TileResetSetter.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/UARTRx.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/UARTToSerial.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/UARTTx.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/cc_banks_0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/cc_banks_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/cc_banks_2.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/cc_banks_3.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/cc_dir.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/data_16x65.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/data_33x41.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/data_40x73.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/head_21x6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/head_2x4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/head_40x6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/mem.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/next_16x4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/next_33x6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/next_40x6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/plusarg_reader.v
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_12x108.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x101.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x107.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x108.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x114.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x115.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x116.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x51.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x60.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x71.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x73.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x79.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x80.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_2x99.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_8x78.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_8x8.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_data_3x64.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/ram_sink_2x3.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/regfile_32x33.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rf_31x32.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_dcache_data_arrays_0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_dcache_data_arrays_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_dcache_tag_array.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_icache_data_arrays_0.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_icache_data_arrays_1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/rockettile_icache_tag_array.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/table_512x1.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/tail_21x6.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/tail_2x4.sv
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/tail_40x6.sv
    }
      rt::read_verilog {
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/chipyard.harness.TestHarness.RV32RocketFPGAConfig.top.mems.v
      /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/RV32RocketFPGAConfig/RV32RocketFPGAConfig/gen-collateral/RV32RocketCoreTop.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top RV32RocketCoreTop
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-91027-Desktop-Home/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
