// Generated by CIRCT firtool-1.75.0
module ChipTop(	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  output        axi4_mmio_0_clock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input         axi4_mmio_0_bits_aw_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_aw_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [3:0]  axi4_mmio_0_bits_aw_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [31:0] axi4_mmio_0_bits_aw_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [7:0]  axi4_mmio_0_bits_aw_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [2:0]  axi4_mmio_0_bits_aw_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [1:0]  axi4_mmio_0_bits_aw_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_aw_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [3:0]  axi4_mmio_0_bits_aw_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [2:0]  axi4_mmio_0_bits_aw_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [3:0]  axi4_mmio_0_bits_aw_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input         axi4_mmio_0_bits_w_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_w_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [63:0] axi4_mmio_0_bits_w_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [7:0]  axi4_mmio_0_bits_w_bits_strb,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_w_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_b_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input         axi4_mmio_0_bits_b_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input  [3:0]  axi4_mmio_0_bits_b_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input  [1:0]  axi4_mmio_0_bits_b_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input         axi4_mmio_0_bits_ar_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_ar_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [3:0]  axi4_mmio_0_bits_ar_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [31:0] axi4_mmio_0_bits_ar_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [7:0]  axi4_mmio_0_bits_ar_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [2:0]  axi4_mmio_0_bits_ar_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [1:0]  axi4_mmio_0_bits_ar_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_ar_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [3:0]  axi4_mmio_0_bits_ar_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [2:0]  axi4_mmio_0_bits_ar_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output [3:0]  axi4_mmio_0_bits_ar_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mmio_0_bits_r_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input         axi4_mmio_0_bits_r_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input  [3:0]  axi4_mmio_0_bits_r_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input  [63:0] axi4_mmio_0_bits_r_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input  [1:0]  axi4_mmio_0_bits_r_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  input         axi4_mmio_0_bits_r_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:416:22]
  output        axi4_mem_0_clock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         axi4_mem_0_bits_aw_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_aw_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [3:0]  axi4_mem_0_bits_aw_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [30:0] axi4_mem_0_bits_aw_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [7:0]  axi4_mem_0_bits_aw_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [2:0]  axi4_mem_0_bits_aw_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [1:0]  axi4_mem_0_bits_aw_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_aw_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [3:0]  axi4_mem_0_bits_aw_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [2:0]  axi4_mem_0_bits_aw_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [3:0]  axi4_mem_0_bits_aw_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         axi4_mem_0_bits_w_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_w_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [63:0] axi4_mem_0_bits_w_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [7:0]  axi4_mem_0_bits_w_bits_strb,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_w_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_b_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         axi4_mem_0_bits_b_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input  [3:0]  axi4_mem_0_bits_b_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input  [1:0]  axi4_mem_0_bits_b_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         axi4_mem_0_bits_ar_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_ar_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [3:0]  axi4_mem_0_bits_ar_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [30:0] axi4_mem_0_bits_ar_bits_addr,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [7:0]  axi4_mem_0_bits_ar_bits_len,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [2:0]  axi4_mem_0_bits_ar_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [1:0]  axi4_mem_0_bits_ar_bits_burst,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_ar_bits_lock,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [3:0]  axi4_mem_0_bits_ar_bits_cache,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [2:0]  axi4_mem_0_bits_ar_bits_prot,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output [3:0]  axi4_mem_0_bits_ar_bits_qos,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  output        axi4_mem_0_bits_r_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         axi4_mem_0_bits_r_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input  [3:0]  axi4_mem_0_bits_r_bits_id,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input  [63:0] axi4_mem_0_bits_r_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input  [1:0]  axi4_mem_0_bits_r_bits_resp,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         axi4_mem_0_bits_r_bits_last,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:397:22]
  input         custom_boot,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         reset_io,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:87:24]
  input         clock_uncore,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:95:26]
  output        clock_tap	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
);

  wire _iocell_custom_boot_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _system_clock_tap;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  DigitalTop system (	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore),
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .auto_mbus_fixedClockNode_anon_out_clock                                           (axi4_mem_0_clock),
    .auto_sbus_fixedClockNode_anon_out_clock                                           (axi4_mmio_0_clock),
    .mem_axi4_0_aw_ready                                                               (axi4_mem_0_bits_aw_ready),
    .mem_axi4_0_aw_valid                                                               (axi4_mem_0_bits_aw_valid),
    .mem_axi4_0_aw_bits_id                                                             (axi4_mem_0_bits_aw_bits_id),
    .mem_axi4_0_aw_bits_addr                                                           (axi4_mem_0_bits_aw_bits_addr),
    .mem_axi4_0_aw_bits_len                                                            (axi4_mem_0_bits_aw_bits_len),
    .mem_axi4_0_aw_bits_size                                                           (axi4_mem_0_bits_aw_bits_size),
    .mem_axi4_0_aw_bits_burst                                                          (axi4_mem_0_bits_aw_bits_burst),
    .mem_axi4_0_aw_bits_lock                                                           (axi4_mem_0_bits_aw_bits_lock),
    .mem_axi4_0_aw_bits_cache                                                          (axi4_mem_0_bits_aw_bits_cache),
    .mem_axi4_0_aw_bits_prot                                                           (axi4_mem_0_bits_aw_bits_prot),
    .mem_axi4_0_aw_bits_qos                                                            (axi4_mem_0_bits_aw_bits_qos),
    .mem_axi4_0_w_ready                                                                (axi4_mem_0_bits_w_ready),
    .mem_axi4_0_w_valid                                                                (axi4_mem_0_bits_w_valid),
    .mem_axi4_0_w_bits_data                                                            (axi4_mem_0_bits_w_bits_data),
    .mem_axi4_0_w_bits_strb                                                            (axi4_mem_0_bits_w_bits_strb),
    .mem_axi4_0_w_bits_last                                                            (axi4_mem_0_bits_w_bits_last),
    .mem_axi4_0_b_ready                                                                (axi4_mem_0_bits_b_ready),
    .mem_axi4_0_b_valid                                                                (axi4_mem_0_bits_b_valid),
    .mem_axi4_0_b_bits_id                                                              (axi4_mem_0_bits_b_bits_id),
    .mem_axi4_0_b_bits_resp                                                            (axi4_mem_0_bits_b_bits_resp),
    .mem_axi4_0_ar_ready                                                               (axi4_mem_0_bits_ar_ready),
    .mem_axi4_0_ar_valid                                                               (axi4_mem_0_bits_ar_valid),
    .mem_axi4_0_ar_bits_id                                                             (axi4_mem_0_bits_ar_bits_id),
    .mem_axi4_0_ar_bits_addr                                                           (axi4_mem_0_bits_ar_bits_addr),
    .mem_axi4_0_ar_bits_len                                                            (axi4_mem_0_bits_ar_bits_len),
    .mem_axi4_0_ar_bits_size                                                           (axi4_mem_0_bits_ar_bits_size),
    .mem_axi4_0_ar_bits_burst                                                          (axi4_mem_0_bits_ar_bits_burst),
    .mem_axi4_0_ar_bits_lock                                                           (axi4_mem_0_bits_ar_bits_lock),
    .mem_axi4_0_ar_bits_cache                                                          (axi4_mem_0_bits_ar_bits_cache),
    .mem_axi4_0_ar_bits_prot                                                           (axi4_mem_0_bits_ar_bits_prot),
    .mem_axi4_0_ar_bits_qos                                                            (axi4_mem_0_bits_ar_bits_qos),
    .mem_axi4_0_r_ready                                                                (axi4_mem_0_bits_r_ready),
    .mem_axi4_0_r_valid                                                                (axi4_mem_0_bits_r_valid),
    .mem_axi4_0_r_bits_id                                                              (axi4_mem_0_bits_r_bits_id),
    .mem_axi4_0_r_bits_data                                                            (axi4_mem_0_bits_r_bits_data),
    .mem_axi4_0_r_bits_resp                                                            (axi4_mem_0_bits_r_bits_resp),
    .mem_axi4_0_r_bits_last                                                            (axi4_mem_0_bits_r_bits_last),
    .mmio_axi4_0_aw_ready                                                              (axi4_mmio_0_bits_aw_ready),
    .mmio_axi4_0_aw_valid                                                              (axi4_mmio_0_bits_aw_valid),
    .mmio_axi4_0_aw_bits_id                                                            (axi4_mmio_0_bits_aw_bits_id),
    .mmio_axi4_0_aw_bits_addr                                                          (axi4_mmio_0_bits_aw_bits_addr),
    .mmio_axi4_0_aw_bits_len                                                           (axi4_mmio_0_bits_aw_bits_len),
    .mmio_axi4_0_aw_bits_size                                                          (axi4_mmio_0_bits_aw_bits_size),
    .mmio_axi4_0_aw_bits_burst                                                         (axi4_mmio_0_bits_aw_bits_burst),
    .mmio_axi4_0_aw_bits_lock                                                          (axi4_mmio_0_bits_aw_bits_lock),
    .mmio_axi4_0_aw_bits_cache                                                         (axi4_mmio_0_bits_aw_bits_cache),
    .mmio_axi4_0_aw_bits_prot                                                          (axi4_mmio_0_bits_aw_bits_prot),
    .mmio_axi4_0_aw_bits_qos                                                           (axi4_mmio_0_bits_aw_bits_qos),
    .mmio_axi4_0_w_ready                                                               (axi4_mmio_0_bits_w_ready),
    .mmio_axi4_0_w_valid                                                               (axi4_mmio_0_bits_w_valid),
    .mmio_axi4_0_w_bits_data                                                           (axi4_mmio_0_bits_w_bits_data),
    .mmio_axi4_0_w_bits_strb                                                           (axi4_mmio_0_bits_w_bits_strb),
    .mmio_axi4_0_w_bits_last                                                           (axi4_mmio_0_bits_w_bits_last),
    .mmio_axi4_0_b_ready                                                               (axi4_mmio_0_bits_b_ready),
    .mmio_axi4_0_b_valid                                                               (axi4_mmio_0_bits_b_valid),
    .mmio_axi4_0_b_bits_id                                                             (axi4_mmio_0_bits_b_bits_id),
    .mmio_axi4_0_b_bits_resp                                                           (axi4_mmio_0_bits_b_bits_resp),
    .mmio_axi4_0_ar_ready                                                              (axi4_mmio_0_bits_ar_ready),
    .mmio_axi4_0_ar_valid                                                              (axi4_mmio_0_bits_ar_valid),
    .mmio_axi4_0_ar_bits_id                                                            (axi4_mmio_0_bits_ar_bits_id),
    .mmio_axi4_0_ar_bits_addr                                                          (axi4_mmio_0_bits_ar_bits_addr),
    .mmio_axi4_0_ar_bits_len                                                           (axi4_mmio_0_bits_ar_bits_len),
    .mmio_axi4_0_ar_bits_size                                                          (axi4_mmio_0_bits_ar_bits_size),
    .mmio_axi4_0_ar_bits_burst                                                         (axi4_mmio_0_bits_ar_bits_burst),
    .mmio_axi4_0_ar_bits_lock                                                          (axi4_mmio_0_bits_ar_bits_lock),
    .mmio_axi4_0_ar_bits_cache                                                         (axi4_mmio_0_bits_ar_bits_cache),
    .mmio_axi4_0_ar_bits_prot                                                          (axi4_mmio_0_bits_ar_bits_prot),
    .mmio_axi4_0_ar_bits_qos                                                           (axi4_mmio_0_bits_ar_bits_qos),
    .mmio_axi4_0_r_ready                                                               (axi4_mmio_0_bits_r_ready),
    .mmio_axi4_0_r_valid                                                               (axi4_mmio_0_bits_r_valid),
    .mmio_axi4_0_r_bits_id                                                             (axi4_mmio_0_bits_r_bits_id),
    .mmio_axi4_0_r_bits_data                                                           (axi4_mmio_0_bits_r_bits_data),
    .mmio_axi4_0_r_bits_resp                                                           (axi4_mmio_0_bits_r_bits_resp),
    .mmio_axi4_0_r_bits_last                                                           (axi4_mmio_0_bits_r_bits_last),
    .custom_boot                                                                       (_iocell_custom_boot_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .clock_tap                                                                         (_system_clock_tap)
  );	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  GenericDigitalInIOCell iocell_custom_boot (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (custom_boot),
    .i   (_iocell_custom_boot_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_clock_tap (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (clock_tap),
    .o   (_system_clock_tap),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
endmodule

