// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FPU(	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
  input  [31:0] io_inst,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [31:0] io_fromint_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [2:0]  io_fcsr_rm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_fcsr_flags_valid,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [4:0]  io_fcsr_flags_bits,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [31:0] io_store_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [31:0] io_toint_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_ll_resp_val,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [2:0]  io_ll_resp_type,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [4:0]  io_ll_resp_tag,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input  [31:0] io_ll_resp_data,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_valid,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_fcsr_rdy,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_nack_mem,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_illegal_rm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_killx,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  input         io_killm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_wen,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_ren1,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_ren2,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_dec_ren3,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_sboard_set,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output        io_sboard_clr,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
  output [4:0]  io_sboard_clra	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
);

  wire             divSqrt_inFlight;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1035:34, :1045:{27,46}]
  wire [4:0]       divSqrt_flags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1037:66, :1040:23]
  wire [32:0]      divSqrt_wdata;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1037:66, :1039:23]
  wire             divSqrt_wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1037:66, :1038:21]
  wire             divSqrt_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1037:37]
  wire             _divSqrt_1_io_inReady;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire             _divSqrt_1_io_outValid_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire             _divSqrt_1_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire [32:0]      _divSqrt_1_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire [4:0]       _divSqrt_1_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire             _divSqrt_io_inReady;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire             _divSqrt_io_outValid_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire             _divSqrt_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire [16:0]      _divSqrt_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire [4:0]       _divSqrt_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  wire [32:0]      _hfma_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:919:28]
  wire [4:0]       _hfma_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:919:28]
  wire [32:0]      _fpmu_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:891:20]
  wire [4:0]       _fpmu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:891:20]
  wire [32:0]      _ifpu_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:886:20]
  wire [4:0]       _ifpu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:886:20]
  wire [2:0]       _fpiu_io_out_bits_in_rm;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  wire [32:0]      _fpiu_io_out_bits_in_in1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  wire [32:0]      _fpiu_io_out_bits_in_in2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  wire             _fpiu_io_out_bits_lt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  wire [4:0]       _fpiu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  wire [32:0]      _sfma_io_out_bits_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:872:20]
  wire [4:0]       _sfma_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:872:20]
  wire [32:0]      _regfile_ext_R0_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
  wire [32:0]      _regfile_ext_R1_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
  wire [32:0]      _regfile_ext_R2_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
  wire             _fp_decoder_io_sigs_ren1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_swap12;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_swap23;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire [1:0]       _fp_decoder_io_sigs_typeTagIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire [1:0]       _fp_decoder_io_sigs_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  wire             _fp_decoder_io_sigs_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  reg              ex_reg_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29]
  reg  [31:0]      ex_reg_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30]
  reg              ex_reg_ctrl_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_swap23;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg  [1:0]       ex_reg_ctrl_typeTagIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg  [1:0]       ex_reg_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg              ex_reg_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
  reg  [4:0]       ex_ra_0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31]
  reg  [4:0]       ex_ra_1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31]
  reg  [4:0]       ex_ra_2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31]
  reg              load_wb;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:773:24]
  reg  [1:0]       load_wb_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:774:34]
  reg  [31:0]      load_wb_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:775:31]
  reg  [4:0]       load_wb_tag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:776:30]
  reg              mem_reg_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:784:30]
  reg  [31:0]      mem_reg_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:791:31]
  reg              wb_reg_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:29]
  reg  [1:0]       mem_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              mem_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
  reg              wb_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:802:26]
  wire [31:0]      _wdata_T_2 = (load_wb_typeTag[0] ? 32'h0 : 32'hFFFF0000) | load_wb_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :774:34, :775:31, generators/rocket-chip/src/main/scala/util/package.scala:38:47, :39:76]
  wire             wdata_rawIn_isZeroExpIn = _wdata_T_2[30:23] == 8'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [4:0]       wdata_rawIn_normDist = _wdata_T_2[22] ? 5'h0 : _wdata_T_2[21] ? 5'h1 : _wdata_T_2[20] ? 5'h2 : _wdata_T_2[19] ? 5'h3 : _wdata_T_2[18] ? 5'h4 : _wdata_T_2[17] ? 5'h5 : _wdata_T_2[16] ? 5'h6 : _wdata_T_2[15] ? 5'h7 : _wdata_T_2[14] ? 5'h8 : _wdata_T_2[13] ? 5'h9 : _wdata_T_2[12] ? 5'hA : _wdata_T_2[11] ? 5'hB : _wdata_T_2[10] ? 5'hC : _wdata_T_2[9] ? 5'hD : _wdata_T_2[8] ? 5'hE : _wdata_T_2[7] ? 5'hF : _wdata_T_2[6] ? 5'h10 : _wdata_T_2[5] ? 5'h11 : _wdata_T_2[4] ? 5'h12 : _wdata_T_2[3] ? 5'h13 : _wdata_T_2[2] ? 5'h14 : _wdata_T_2[1] ? 5'h15 : 5'h16;	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [53:0]      _wdata_rawIn_subnormFract_T = {31'h0, _wdata_T_2[22:0]} << wdata_rawIn_normDist;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [8:0]       _wdata_rawIn_adjustedExp_T_4 = (wdata_rawIn_isZeroExpIn ? {4'hF, ~wdata_rawIn_normDist} : {1'h0, _wdata_T_2[30:23]}) + {7'h20, wdata_rawIn_isZeroExpIn ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [22:0]      _wdata_rawIn_out_sig_T_2 = wdata_rawIn_isZeroExpIn ? {_wdata_rawIn_subnormFract_T[21:0], 1'h0} : _wdata_T_2[22:0];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :52:{33,46,64}, :70:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [2:0]       _wdata_T_4 = wdata_rawIn_isZeroExpIn & ~(|(_wdata_T_2[22:0])) ? 3'h0 : _wdata_rawIn_adjustedExp_T_4[8:6];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :735:7]
  wire             _GEN = _wdata_T_4[0] | (&(_wdata_rawIn_adjustedExp_T_4[8:7])) & (|(_wdata_T_2[22:0]));	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :49:34, :57:9, :61:{32,57}, :64:28, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire             wdata_rawIn_isZeroExpIn_1 = _wdata_T_2[14:10] == 5'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23]
  wire [3:0]       wdata_rawIn_normDist_1 = _wdata_T_2[9] ? 4'h0 : _wdata_T_2[8] ? 4'h1 : _wdata_T_2[7] ? 4'h2 : _wdata_T_2[6] ? 4'h3 : _wdata_T_2[5] ? 4'h4 : _wdata_T_2[4] ? 4'h5 : _wdata_T_2[3] ? 4'h6 : _wdata_T_2[2] ? 4'h7 : {3'h4, ~(_wdata_T_2[1])};	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:91:52, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :735:7, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [24:0]      _wdata_rawIn_subnormFract_T_2 = {15'h0, _wdata_T_2[9:0]} << wdata_rawIn_normDist_1;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :52:33, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [5:0]       _wdata_rawIn_adjustedExp_T_9 = (wdata_rawIn_isZeroExpIn_1 ? {2'h3, ~wdata_rawIn_normDist_1} : {1'h0, _wdata_T_2[14:10]}) + {4'h4, wdata_rawIn_isZeroExpIn_1 ? 2'h2 : 2'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:45:19, :48:30, :54:10, :55:18, :57:9, :58:14, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, src/main/scala/chisel3/util/Mux.scala:50:70]
  wire [2:0]       _wdata_T_13 = wdata_rawIn_isZeroExpIn_1 & ~(|(_wdata_T_2[9:0])) ? 3'h0 : _wdata_rawIn_adjustedExp_T_9[5:3];	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:46:21, :48:30, :49:34, :57:9, :60:30, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,50}, generators/rocket-chip/src/main/scala/tile/FPU.scala:431:23, :735:7]
  wire [28:0]      _GEN_0 = (&{_wdata_T_4[2:1], _GEN}) ? {&(_wdata_rawIn_out_sig_T_2[22:16]), _wdata_rawIn_adjustedExp_T_4[4:1], _wdata_T_13[2], _wdata_rawIn_out_sig_T_2[22:16], _wdata_T_2[15], _wdata_T_13[1], _wdata_T_13[0] | (&(_wdata_rawIn_adjustedExp_T_9[5:4])) & (|(_wdata_T_2[9:0])), _wdata_rawIn_adjustedExp_T_9[2:0], wdata_rawIn_isZeroExpIn_1 ? {_wdata_rawIn_subnormFract_T_2[8:0], 1'h0} : _wdata_T_2[9:0]} : {_wdata_rawIn_adjustedExp_T_4[5:0], _wdata_rawIn_out_sig_T_2};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, :46:21, :48:30, :49:34, :52:{33,46,64}, :57:9, :61:{32,57}, :64:28, :70:33, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, :50:{23,41}, generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :336:26, :338:{8,42}, :339:8, :340:8, :343:8, :344:8, :431:23]
  wire [2:0]       ex_rm = (&(ex_reg_inst[14:12])) ? io_fcsr_rm : ex_reg_inst[14:12];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30, :845:{18,30,38}]
  wire             _hfma_io_in_valid_T = ex_reg_valid & ex_reg_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29, :769:30, :873:33]
  wire [2:0]       fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode = {_regfile_ext_R2_data[23], _regfile_ext_R2_data[14:13]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14, :818:20]
  wire [8:0]       _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2 = {3'h0, _regfile_ext_R2_data[23], _regfile_ext_R2_data[14:10]} + 9'hE0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14, :735:7, :818:20]
  wire [32:0]      fpmu_io_in_bits_in1 = ex_reg_ctrl_typeTagIn[0] | (&(_regfile_ext_R2_data[32:28])) ? (ex_reg_ctrl_typeTagIn[0] ? _regfile_ext_R2_data : {_regfile_ext_R2_data[15], fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode > 3'h5 ? {_regfile_ext_R2_data[23], _regfile_ext_R2_data[14:13], _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2[5:0]} : _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2, _regfile_ext_R2_data[9:0], 13'h0}) : 33'hE0400000;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:275:20, :276:18, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :332:{49,84}, :357:14, :358:14, :369:10, :735:7, :769:30, :818:20, generators/rocket-chip/src/main/scala/util/package.scala:38:47, :39:76]
  wire [2:0]       fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode = {_regfile_ext_R1_data[23], _regfile_ext_R1_data[14:13]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14, :818:20]
  wire [8:0]       _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2 = {3'h0, _regfile_ext_R1_data[23], _regfile_ext_R1_data[14:10]} + 9'hE0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :358:14, :735:7, :818:20]
  wire [32:0]      fpmu_io_in_bits_in2 = ex_reg_ctrl_typeTagIn[0] | (&(_regfile_ext_R1_data[32:28])) ? (ex_reg_ctrl_typeTagIn[0] ? _regfile_ext_R1_data : {_regfile_ext_R1_data[15], fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode > 3'h5 ? {_regfile_ext_R1_data[23], _regfile_ext_R1_data[14:13], _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2[5:0]} : _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2, _regfile_ext_R1_data[9:0], 13'h0}) : 33'hE0400000;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:275:20, :276:18, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :332:{49,84}, :357:14, :358:14, :369:10, :735:7, :769:30, :818:20, generators/rocket-chip/src/main/scala/util/package.scala:38:47, :39:76]
  reg  [4:0]       divSqrt_waddr;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:898:26]
  wire             _divSqrt_io_inValid_T_2 = mem_ctrl_typeTagOut == 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :911:72]
  wire             _divSqrt_io_inValid_T = mem_ctrl_typeTagOut == 2'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :922:78]
  reg  [1:0]       wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:939:20]
  reg  [4:0]       wbInfo_0_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg              wbInfo_0_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg              wbInfo_0_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg  [1:0]       wbInfo_0_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg  [4:0]       wbInfo_1_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg              wbInfo_1_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg              wbInfo_1_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg  [1:0]       wbInfo_1_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
  reg              write_port_busy;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:942:34]
  wire [4:0]       waddr = divSqrt_wen ? divSqrt_waddr : wbInfo_0_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:898:26, :940:19, :963:18, :1037:66, :1038:21]
  wire [3:0][32:0] _GEN_1 = {{_hfma_io_out_bits_data}, {_sfma_io_out_bits_data}, {_ifpu_io_out_bits_data}, {_fpmu_io_out_bits_data}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:872:20, :886:20, :891:20, :919:28, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire [32:0]      _wdata_T_29 = divSqrt_wen ? divSqrt_wdata : _GEN_1[wbInfo_0_pipeid];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19, :966:22, :1037:66, :1038:21, :1039:23, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire [32:0]      wdata_1 = (divSqrt_wen ? divSqrt_typeTag : wbInfo_0_typeTag) ? _wdata_T_29 : {9'h1FF, _wdata_T_29[15], 7'h7F, _wdata_T_29[16], _wdata_T_29[14:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:336:26, :340:8, :342:8, :343:8, :940:19, :965:21, :966:22, :1037:{37,66}, :1038:21, generators/rocket-chip/src/main/scala/util/package.scala:39:76]
  wire [3:0][4:0]  _GEN_2 = {{_hfma_io_out_bits_exc}, {_sfma_io_out_bits_exc}, {_ifpu_io_out_bits_exc}, {_fpmu_io_out_bits_exc}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:872:20, :886:20, :891:20, :919:28, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  wire             _GEN_3 = ~wbInfo_0_cp & wen[0] | divSqrt_wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:939:20, :940:19, :968:{10,24,30,35}, :1037:66, :1038:21]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:822:11]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:822:11]
      if (load_wb & ~reset & ~({_wdata_T_4[2:1], _GEN} != 3'h7 | _GEN_0[28] == (&(_GEN_0[22:16])))) begin	// @[generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :344:8, :385:{31,35,55,60,96}, :735:7, :773:24, :822:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:822:11]
          $error("Assertion failed\n    at FPU.scala:822 assert(consistent(wdata))\n");	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:822:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:822:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:822:11]
      end
      if (_GEN_3 & ~reset & ~(wdata_1[31:29] != 3'h7 | wdata_1[28] == (&(wdata_1[22:16])))) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :385:{31,35,55,60,96}, :735:7, :822:11, :968:35, :969:11, generators/rocket-chip/src/main/scala/util/package.scala:39:76]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:969:11]
          $error("Assertion failed\n    at FPU.scala:969 assert(consistent(wdata))\n");	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:969:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:969:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:969:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire             wb_toint_valid = wb_reg_valid & wb_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:29, :802:26, :993:37]
  reg  [4:0]       wb_toint_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:994:31]
  wire             _divSqrt_inValid_T = mem_ctrl_div | mem_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :1001:47]
  wire             io_nack_mem_0 = write_port_busy | _divSqrt_inValid_T & (|wen) | divSqrt_inFlight;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:939:20, :942:34, :1001:{47,65,72}, :1003:{35,62}, :1035:34, :1045:{27,46}]
  reg              io_sboard_set_REG;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1006:59]
  wire             divSqrt_inValid = mem_reg_valid & _divSqrt_inValid_T & ~divSqrt_inFlight;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:784:30, :991:74, :1001:47, :1014:{41,76}, :1035:34, :1045:{27,46}]
  reg              divSqrt_killed;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1015:33]
  wire [5:0]       _divSqrt_io_a_expOut_commonCase_T = _fpiu_io_out_bits_in_in1[28:23] - 6'h20;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:31, :876:20]
  wire [5:0]       _divSqrt_io_b_expOut_commonCase_T = _fpiu_io_out_bits_in_in2[28:23] - 6'h20;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:31, :876:20]
  assign divSqrt_typeTag = _divSqrt_1_io_outValid_div | _divSqrt_1_io_outValid_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55, :1037:37]
  assign divSqrt_wen = divSqrt_typeTag ? ~divSqrt_killed : (_divSqrt_io_outValid_div | _divSqrt_io_outValid_sqrt) & ~divSqrt_killed;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:896:32, :1015:33, :1027:55, :1037:{37,66}, :1038:{21,24}]
  assign divSqrt_wdata = divSqrt_typeTag ? ({33{_divSqrt_1_io_out[31:29] != 3'h7}} | 33'h1EF7FFFFF) & _divSqrt_1_io_out : {16'h0, _divSqrt_io_out};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:249:{25,56}, :414:10, :735:7, :852:13, :1027:55, :1037:{37,66}, :1039:23]
  assign divSqrt_flags = divSqrt_typeTag ? _divSqrt_1_io_exceptionFlags : _divSqrt_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55, :1037:{37,66}, :1040:23]
  assign divSqrt_inFlight = ~divSqrt_killed & (~_divSqrt_1_io_inReady | ~_divSqrt_io_inReady);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1015:33, :1027:55, :1035:{13,34,53}, :1045:{27,46}]
  wire             _killm_T = io_killm | io_nack_mem_0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:25, :1003:{35,62}]
  wire             _memLatencyMask_T_8 = mem_ctrl_fastpipe | mem_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :926:72]
  wire             _GEN_4 = mem_ctrl_fma & _divSqrt_io_inValid_T_2 | mem_ctrl_fma & _divSqrt_io_inValid_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :911:{56,72}, :922:{62,78}, :926:72]
  wire             mem_wen = mem_reg_valid & (mem_ctrl_fma | mem_ctrl_fastpipe | mem_ctrl_fromint);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:784:30, :801:27, :941:{31,48,69}]
  wire             _GEN_5 = mem_wen & ~write_port_busy & _memLatencyMask_T_8;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:926:72, :941:31, :942:34, :946:21, :949:18, :954:{13,30,52}, :955:22]
  wire             _GEN_6 = mem_wen & ~write_port_busy & _GEN_4;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:926:72, :940:19, :941:31, :942:34, :949:18, :954:{13,30,52}, :955:22]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      ex_reg_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29]
      mem_reg_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:784:30]
      wb_reg_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:792:29]
      wen <= 2'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:939:20]
      divSqrt_killed <= 1'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1015:33]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      ex_reg_valid <= io_valid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29]
      mem_reg_valid <= ex_reg_valid & ~(io_killx | mem_reg_valid & _killm_T);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29, :784:30, :785:25, :789:{24,41}, :790:{33,36}]
      wb_reg_valid <= mem_reg_valid & ~_killm_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:784:30, :785:25, :792:{29,44,48}]
      wen <= mem_wen & ~_killm_T ? {_GEN_4, wen[1] | _memLatencyMask_T_8} : {1'h0, wen[1]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:25, :792:48, :926:72, :939:20, :941:31, :948:{7,14}, :949:18, :950:19, :951:{11,23}]
      divSqrt_killed <= divSqrt_inValid & _killm_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:785:25, :1014:{41,76}, :1015:{33,50}]
    end
    if (io_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
      ex_reg_inst <= io_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30]
      ex_reg_ctrl_ren2 <= _fp_decoder_io_sigs_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_ren3 <= _fp_decoder_io_sigs_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_swap23 <= _fp_decoder_io_sigs_swap23;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_typeTagIn <= _fp_decoder_io_sigs_typeTagIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_typeTagOut <= _fp_decoder_io_sigs_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_fromint <= _fp_decoder_io_sigs_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_toint <= _fp_decoder_io_sigs_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_fastpipe <= _fp_decoder_io_sigs_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_fma <= _fp_decoder_io_sigs_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_div <= _fp_decoder_io_sigs_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_sqrt <= _fp_decoder_io_sigs_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_wflags <= _fp_decoder_io_sigs_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      ex_reg_ctrl_vec <= _fp_decoder_io_sigs_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :769:30]
      if (_fp_decoder_io_sigs_ren2 & _fp_decoder_io_sigs_swap12)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :834:25, :838:25, :839:{29,40}]
        ex_ra_0 <= io_inst[24:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31, :839:50]
      else if (_fp_decoder_io_sigs_ren1 & ~_fp_decoder_io_sigs_swap12)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:31, :834:25, :835:{13,30,41}]
        ex_ra_0 <= io_inst[19:15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31, :835:51]
      if (_fp_decoder_io_sigs_ren2 & ~_fp_decoder_io_sigs_swap12 & ~_fp_decoder_io_sigs_swap23)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :834:25, :835:13, :838:25, :841:{29,32,49,60}]
        ex_ra_1 <= io_inst[24:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31, :841:70]
      else if (_fp_decoder_io_sigs_ren1 & _fp_decoder_io_sigs_swap12)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:31, :834:25, :836:{29,40}]
        ex_ra_1 <= io_inst[19:15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31, :836:50]
      if (_fp_decoder_io_sigs_ren3)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
        ex_ra_2 <= io_inst[31:27];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31, :843:46]
      else if (_fp_decoder_io_sigs_ren2 & _fp_decoder_io_sigs_swap23)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26, :770:31, :838:25, :840:{29,40}]
        ex_ra_2 <= io_inst[24:20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31, :840:50]
    end
    load_wb <= io_ll_resp_val;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:773:24]
    if (io_ll_resp_val) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:736:14]
      load_wb_typeTag <= io_ll_resp_type[1:0] - 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:774:{34,50,56}]
      load_wb_data <= io_ll_resp_data;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:775:31]
      load_wb_tag <= io_ll_resp_tag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:776:30]
    end
    if (ex_reg_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29]
      mem_reg_inst <= ex_reg_inst;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30, :791:31]
      mem_ctrl_typeTagOut <= ex_reg_ctrl_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_fromint <= ex_reg_ctrl_fromint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_toint <= ex_reg_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_fastpipe <= ex_reg_ctrl_fastpipe;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_fma <= ex_reg_ctrl_fma;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_div <= ex_reg_ctrl_div;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_sqrt <= ex_reg_ctrl_sqrt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_wflags <= ex_reg_ctrl_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      mem_ctrl_vec <= ex_reg_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :801:27]
      write_port_busy <= mem_wen & (ex_reg_ctrl_fastpipe | ex_reg_ctrl_fromint) & _GEN_4;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :926:72, :941:31, :942:{34,43,62}]
    end
    if (mem_reg_valid)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:784:30]
      wb_ctrl_toint <= mem_ctrl_toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :802:26]
    if (divSqrt_inValid)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1014:{41,76}]
      divSqrt_waddr <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:791:31, :898:26, :1017:36]
    if (_GEN_5) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:946:21, :949:18, :954:{30,52}, :955:22]
      wbInfo_0_rd <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:791:31, :940:19, :958:37]
      wbInfo_0_typeTag <= mem_ctrl_typeTagOut[0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :940:19, :956:27]
      wbInfo_0_pipeid <= {mem_ctrl_fma & _divSqrt_io_inValid_T_2, mem_ctrl_fromint} | {2{mem_ctrl_fma & _divSqrt_io_inValid_T}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :911:{56,72}, :922:{62,78}, :928:{63,100}, :940:19]
    end
    else if (wen[1]) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:939:20, :946:14]
      wbInfo_0_rd <= wbInfo_1_rd;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
      wbInfo_0_typeTag <= wbInfo_1_typeTag;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
      wbInfo_0_pipeid <= wbInfo_1_pipeid;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19]
    end
    wbInfo_0_cp <= ~_GEN_5 & (wen[1] ? wbInfo_1_cp : wbInfo_0_cp);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:939:20, :940:19, :946:{14,21,33}, :949:18, :954:{30,52}, :955:22]
    if (_GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19, :949:18, :954:{30,52}, :955:22]
      wbInfo_1_rd <= mem_reg_inst[11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:791:31, :940:19, :958:37]
      wbInfo_1_typeTag <= mem_ctrl_typeTagOut[0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :940:19, :956:27]
      wbInfo_1_pipeid <= {mem_ctrl_fma & _divSqrt_io_inValid_T_2, mem_ctrl_fromint} | {2{mem_ctrl_fma & _divSqrt_io_inValid_T}};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :911:{56,72}, :922:{62,78}, :928:{63,100}, :940:19]
    end
    wbInfo_1_cp <= ~_GEN_6 & wbInfo_1_cp;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:940:19, :949:18, :954:{30,52}, :955:22]
    if (mem_ctrl_toint)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
      wb_toint_exc <= _fpiu_io_out_bits_exc;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20, :994:31]
    io_sboard_set_REG <= mem_ctrl_div | mem_ctrl_sqrt | mem_ctrl_vec;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27, :1006:{59,111,128}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        end	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
        ex_reg_valid = _RANDOM[3'h0][1];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :767:29]
        ex_reg_inst = {_RANDOM[3'h0][31:2], _RANDOM[3'h1][1:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :767:29, :768:30]
        ex_reg_ctrl_ren2 = _RANDOM[3'h1][5];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_ren3 = _RANDOM[3'h1][6];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_swap23 = _RANDOM[3'h1][8];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_typeTagIn = _RANDOM[3'h1][10:9];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_typeTagOut = _RANDOM[3'h1][12:11];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_fromint = _RANDOM[3'h1][13];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_toint = _RANDOM[3'h1][14];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_fastpipe = _RANDOM[3'h1][15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_fma = _RANDOM[3'h1][16];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_div = _RANDOM[3'h1][17];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_sqrt = _RANDOM[3'h1][18];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_wflags = _RANDOM[3'h1][19];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_reg_ctrl_vec = _RANDOM[3'h1][20];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :769:30]
        ex_ra_0 = _RANDOM[3'h1][25:21];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :770:31]
        ex_ra_1 = _RANDOM[3'h1][30:26];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :770:31]
        ex_ra_2 = {_RANDOM[3'h1][31], _RANDOM[3'h2][3:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :768:30, :770:31]
        load_wb = _RANDOM[3'h2][4];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :770:31, :773:24]
        load_wb_typeTag = _RANDOM[3'h2][6:5];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :770:31, :774:34]
        load_wb_data = {_RANDOM[3'h2][31:7], _RANDOM[3'h3][6:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :770:31, :775:31]
        load_wb_tag = _RANDOM[3'h3][11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :775:31, :776:30]
        mem_reg_valid = _RANDOM[3'h3][14];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :775:31, :784:30]
        mem_reg_inst = {_RANDOM[3'h3][31:15], _RANDOM[3'h4][14:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :775:31, :791:31]
        wb_reg_valid = _RANDOM[3'h4][15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :792:29]
        mem_ctrl_typeTagOut = _RANDOM[3'h4][26:25];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :801:27]
        mem_ctrl_fromint = _RANDOM[3'h4][27];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :801:27]
        mem_ctrl_toint = _RANDOM[3'h4][28];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :801:27]
        mem_ctrl_fastpipe = _RANDOM[3'h4][29];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :801:27]
        mem_ctrl_fma = _RANDOM[3'h4][30];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :801:27]
        mem_ctrl_div = _RANDOM[3'h4][31];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :791:31, :801:27]
        mem_ctrl_sqrt = _RANDOM[3'h5][0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27]
        mem_ctrl_wflags = _RANDOM[3'h5][1];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27]
        mem_ctrl_vec = _RANDOM[3'h5][2];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27]
        wb_ctrl_toint = _RANDOM[3'h5][15];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27, :802:26]
        divSqrt_waddr = _RANDOM[3'h5][26:22];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27, :898:26]
        wen = _RANDOM[3'h5][29:28];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27, :939:20]
        wbInfo_0_rd = {_RANDOM[3'h5][31:30], _RANDOM[3'h6][2:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :801:27, :940:19]
        wbInfo_0_typeTag = _RANDOM[3'h6][3];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        wbInfo_0_cp = _RANDOM[3'h6][4];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        wbInfo_0_pipeid = _RANDOM[3'h6][6:5];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        wbInfo_1_rd = _RANDOM[3'h6][11:7];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        wbInfo_1_typeTag = _RANDOM[3'h6][12];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        wbInfo_1_cp = _RANDOM[3'h6][13];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        wbInfo_1_pipeid = _RANDOM[3'h6][15:14];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19]
        write_port_busy = _RANDOM[3'h6][16];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19, :942:34]
        wb_toint_exc = _RANDOM[3'h6][21:17];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19, :994:31]
        io_sboard_set_REG = _RANDOM[3'h6][22];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19, :1006:59]
        divSqrt_killed = _RANDOM[3'h6][23];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :940:19, :1015:33]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FPUDecoder fp_decoder (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
    .io_inst            (io_inst),
    .io_sigs_wen        (io_dec_wen),
    .io_sigs_ren1       (_fp_decoder_io_sigs_ren1),
    .io_sigs_ren2       (_fp_decoder_io_sigs_ren2),
    .io_sigs_ren3       (_fp_decoder_io_sigs_ren3),
    .io_sigs_swap12     (_fp_decoder_io_sigs_swap12),
    .io_sigs_swap23     (_fp_decoder_io_sigs_swap23),
    .io_sigs_typeTagIn  (_fp_decoder_io_sigs_typeTagIn),
    .io_sigs_typeTagOut (_fp_decoder_io_sigs_typeTagOut),
    .io_sigs_fromint    (_fp_decoder_io_sigs_fromint),
    .io_sigs_toint      (_fp_decoder_io_sigs_toint),
    .io_sigs_fastpipe   (_fp_decoder_io_sigs_fastpipe),
    .io_sigs_fma        (_fp_decoder_io_sigs_fma),
    .io_sigs_div        (_fp_decoder_io_sigs_div),
    .io_sigs_sqrt       (_fp_decoder_io_sigs_sqrt),
    .io_sigs_wflags     (_fp_decoder_io_sigs_wflags),
    .io_sigs_vec        (_fp_decoder_io_sigs_vec)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:750:26]
  regfile_32x33 regfile_ext (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
    .R0_addr (ex_ra_2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31]
    .R0_en   (1'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    .R0_clk  (clock),
    .R0_data (_regfile_ext_R0_data),
    .R1_addr (ex_ra_1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31]
    .R1_en   (1'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    .R1_clk  (clock),
    .R1_data (_regfile_ext_R1_data),
    .R2_addr (ex_ra_0),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:770:31]
    .R2_en   (1'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7]
    .R2_clk  (clock),
    .R2_data (_regfile_ext_R2_data),
    .W0_addr (waddr),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:963:18]
    .W0_en   (_GEN_3),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:968:35]
    .W0_clk  (clock),
    .W0_data (wdata_1),	// @[generators/rocket-chip/src/main/scala/util/package.scala:39:76]
    .W1_addr (load_wb_tag),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:776:30]
    .W1_en   (load_wb),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:773:24]
    .W1_clk  (clock),
    .W1_data ({_wdata_T_2[31], _wdata_T_4[2:1], _GEN, _GEN_0})	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromFN.scala:44:18, generators/hardfloat/hardfloat/src/main/scala/recFNFromFN.scala:48:{15,76}, generators/rocket-chip/src/main/scala/tile/FPU.scala:344:8, :431:23]
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
  FPUFMAPipe_l3_f32 sfma (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:872:20]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_hfma_io_in_valid_T & ex_reg_ctrl_typeTagOut == 2'h1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :873:{33,48,70}]
    .io_in_bits_ren3   (ex_reg_ctrl_ren3),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_swap23 (ex_reg_ctrl_swap23),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_rm     (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:845:18]
    .io_in_bits_fmaCmd ({ex_reg_inst[3], ex_reg_inst[2] | ~ex_reg_ctrl_ren3 & ex_reg_inst[27]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30, :769:30, :857:{30,36,39,53,67}]
    .io_in_bits_in1    (_regfile_ext_R2_data),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
    .io_in_bits_in2    (_regfile_ext_R1_data),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
    .io_in_bits_in3    (_regfile_ext_R0_data),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:818:20]
    .io_out_bits_data  (_sfma_io_out_bits_data),
    .io_out_bits_exc   (_sfma_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:872:20]
  FPToInt fpiu (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
    .clock                 (clock),
    .io_in_valid           (ex_reg_valid & (ex_reg_ctrl_toint | ex_reg_ctrl_div | ex_reg_ctrl_sqrt | ex_reg_ctrl_fastpipe & ex_reg_ctrl_wflags)),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29, :769:30, :877:{33,51,66,82,103}]
    .io_in_bits_ren2       (ex_reg_ctrl_ren2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_typeTagOut (ex_reg_ctrl_typeTagOut),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_wflags     (ex_reg_ctrl_wflags),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_rm         (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:845:18]
    .io_in_bits_typ        (ex_reg_inst[21:20]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30, :855:27]
    .io_in_bits_in1        (fpmu_io_in_bits_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_in_bits_in2        (fpmu_io_in_bits_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_out_bits_in_rm     (_fpiu_io_out_bits_in_rm),
    .io_out_bits_in_in1    (_fpiu_io_out_bits_in_in1),
    .io_out_bits_in_in2    (_fpiu_io_out_bits_in_in2),
    .io_out_bits_lt        (_fpiu_io_out_bits_lt),
    .io_out_bits_store     (io_store_data),
    .io_out_bits_toint     (io_toint_data),
    .io_out_bits_exc       (_fpiu_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  IntToFP ifpu (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:886:20]
    .clock                (clock),
    .reset                (reset),
    .io_in_valid          (ex_reg_valid & ex_reg_ctrl_fromint),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29, :769:30, :887:33]
    .io_in_bits_typeTagIn (ex_reg_ctrl_typeTagIn),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_wflags    (ex_reg_ctrl_wflags),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_rm        (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:845:18]
    .io_in_bits_typ       (ex_reg_inst[21:20]),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30, :855:27]
    .io_in_bits_in1       (io_fromint_data),
    .io_out_bits_data     (_ifpu_io_out_bits_data),
    .io_out_bits_exc      (_ifpu_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:886:20]
  FPToFP fpmu (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:891:20]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (ex_reg_valid & ex_reg_ctrl_fastpipe),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:767:29, :769:30, :892:33]
    .io_in_bits_ren2       (ex_reg_ctrl_ren2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_typeTagOut (ex_reg_ctrl_typeTagOut),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_wflags     (ex_reg_ctrl_wflags),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_rm         (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:845:18]
    .io_in_bits_in1        (fpmu_io_in_bits_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_in_bits_in2        (fpmu_io_in_bits_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10]
    .io_out_bits_data      (_fpmu_io_out_bits_data),
    .io_out_bits_exc       (_fpmu_io_out_bits_exc),
    .io_lt                 (_fpiu_io_out_bits_lt)	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:891:20]
  FPUFMAPipe_l3_f16 hfma (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:919:28]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_hfma_io_in_valid_T & ex_reg_ctrl_typeTagOut == 2'h0),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30, :873:33, :920:{56,78}]
    .io_in_bits_ren3   (ex_reg_ctrl_ren3),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_swap23 (ex_reg_ctrl_swap23),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:769:30]
    .io_in_bits_rm     (ex_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:845:18]
    .io_in_bits_fmaCmd ({ex_reg_inst[3], ex_reg_inst[2] | ~ex_reg_ctrl_ren3 & ex_reg_inst[27]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:768:30, :769:30, :857:{30,36,39,53,67}]
    .io_in_bits_in1    ({16'h0, {_regfile_ext_R2_data[15], _regfile_ext_R2_data[23], _regfile_ext_R2_data[14:0]} | ((&(_regfile_ext_R2_data[32:28])) ? 17'h0 : 17'hE200)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}, :818:20, :852:13]
    .io_in_bits_in2    ({16'h0, {_regfile_ext_R1_data[15], _regfile_ext_R1_data[23], _regfile_ext_R1_data[14:0]} | ((&(_regfile_ext_R1_data[32:28])) ? 17'h0 : 17'hE200)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}, :818:20, :852:13, :853:13]
    .io_in_bits_in3    ({16'h0, {_regfile_ext_R0_data[15], _regfile_ext_R0_data[23], _regfile_ext_R0_data[14:0]} | ((&(_regfile_ext_R0_data[32:28])) ? 17'h0 : 17'hE200)}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}, :818:20, :852:13, :854:13]
    .io_out_bits_data  (_hfma_io_out_bits_data),
    .io_out_bits_exc   (_hfma_io_out_bits_exc)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:919:28]
  DivSqrtRecFM_small_e5_s11 divSqrt (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
    .clock             (clock),
    .reset             (divSqrt_killed),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1015:33]
    .io_inReady        (_divSqrt_io_inReady),
    .io_inValid        (divSqrt_inValid & _divSqrt_io_inValid_T),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:922:78, :1014:{41,76}, :1028:45]
    .io_sqrtOp         (mem_ctrl_sqrt),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
    .io_a              ({_fpiu_io_out_bits_in_in1[32], _fpiu_io_out_bits_in_in1[31:29] == 3'h0 | _fpiu_io_out_bits_in_in1[31:29] > 3'h5 ? {_fpiu_io_out_bits_in_in1[31:29], _divSqrt_io_a_expOut_commonCase_T[2:0]} : _divSqrt_io_a_expOut_commonCase_T, _fpiu_io_out_bits_in_in1[22:13]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:274:17, :276:18, :277:38, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :735:7, :876:20]
    .io_b              ({_fpiu_io_out_bits_in_in2[32], _fpiu_io_out_bits_in_in2[31:29] == 3'h0 | _fpiu_io_out_bits_in_in2[31:29] > 3'h5 ? {_fpiu_io_out_bits_in_in2[31:29], _divSqrt_io_b_expOut_commonCase_T[2:0]} : _divSqrt_io_b_expOut_commonCase_T, _fpiu_io_out_bits_in_in2[22:13]}),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:274:17, :276:18, :277:38, :279:26, :280:{31,50}, :281:{10,19,27,38,49,69}, :283:8, :735:7, :876:20]
    .io_roundingMode   (_fpiu_io_out_bits_in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
    .io_outValid_div   (_divSqrt_io_outValid_div),
    .io_outValid_sqrt  (_divSqrt_io_outValid_sqrt),
    .io_out            (_divSqrt_io_out),
    .io_exceptionFlags (_divSqrt_io_exceptionFlags)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  DivSqrtRecFM_small_e8_s24 divSqrt_1 (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
    .clock             (clock),
    .reset             (divSqrt_killed),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1015:33]
    .io_inReady        (_divSqrt_1_io_inReady),
    .io_inValid        (divSqrt_inValid & _divSqrt_io_inValid_T_2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:911:72, :1014:{41,76}, :1028:45]
    .io_sqrtOp         (mem_ctrl_sqrt),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:801:27]
    .io_a              (_fpiu_io_out_bits_in_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
    .io_b              (_fpiu_io_out_bits_in_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
    .io_roundingMode   (_fpiu_io_out_bits_in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:876:20]
    .io_outValid_div   (_divSqrt_1_io_outValid_div),
    .io_outValid_sqrt  (_divSqrt_1_io_outValid_sqrt),
    .io_out            (_divSqrt_1_io_out),
    .io_exceptionFlags (_divSqrt_1_io_exceptionFlags)
  );	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:1027:55]
  assign io_fcsr_flags_valid = wb_toint_valid | divSqrt_wen | wen[0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :939:20, :968:30, :993:37, :995:{41,56}, :1037:66, :1038:21]
  assign io_fcsr_flags_bits = (wb_toint_valid ? wb_toint_exc : 5'h0) | (divSqrt_wen ? divSqrt_flags : 5'h0) | (wen[0] ? _GEN_2[wbInfo_0_pipeid] : 5'h0);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :939:20, :940:19, :968:30, :993:37, :994:31, :997:{8,44}, :998:{8,42}, :999:8, :1037:66, :1038:21, :1040:23, generators/rocket-chip/src/main/scala/util/package.scala:39:{76,86}]
  assign io_fcsr_rdy = ~((|{ex_reg_valid & ex_reg_ctrl_wflags | mem_reg_valid & mem_ctrl_wflags | wb_toint_valid, wen}) | divSqrt_inFlight);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :767:29, :769:30, :784:30, :801:27, :939:20, :993:37, :1001:72, :1002:{18,33,51,68,87,120,131}, :1035:34, :1045:{27,46}]
  assign io_nack_mem = io_nack_mem_0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1003:{35,62}]
  assign io_illegal_rm = io_inst[14:12] == 3'h5 | io_inst[14:12] == 3'h6 | (&(io_inst[14:12])) & io_fcsr_rm > 3'h4;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1011:{27,53,71,79,93}, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59]
  assign io_dec_ren1 = _fp_decoder_io_sigs_ren1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :750:26]
  assign io_dec_ren2 = _fp_decoder_io_sigs_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :750:26]
  assign io_dec_ren3 = _fp_decoder_io_sigs_ren3;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :750:26]
  assign io_sboard_set = wb_reg_valid & io_sboard_set_REG;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :792:29, :1006:{49,59}]
  assign io_sboard_clr = divSqrt_wen;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :1037:66, :1038:21]
  assign io_sboard_clra = waddr;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:735:7, :963:18]
endmodule

