// Generated by CIRCT firtool-1.75.0
module SimAXIMem(	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:138:7]
  input         clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:138:7]
  input         reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:138:7]
  output        io_axi4_0_aw_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_aw_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [3:0]  io_axi4_0_aw_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [27:0] io_axi4_0_aw_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [7:0]  io_axi4_0_aw_bits_len,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [2:0]  io_axi4_0_aw_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [1:0]  io_axi4_0_aw_bits_burst,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_aw_bits_lock,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [3:0]  io_axi4_0_aw_bits_cache,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [2:0]  io_axi4_0_aw_bits_prot,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [3:0]  io_axi4_0_aw_bits_qos,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output        io_axi4_0_w_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_w_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [63:0] io_axi4_0_w_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [7:0]  io_axi4_0_w_bits_strb,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_w_bits_last,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output        io_axi4_0_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output [3:0]  io_axi4_0_b_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output [1:0]  io_axi4_0_b_bits_resp,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output        io_axi4_0_ar_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_ar_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [3:0]  io_axi4_0_ar_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [27:0] io_axi4_0_ar_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [7:0]  io_axi4_0_ar_bits_len,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [2:0]  io_axi4_0_ar_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [1:0]  io_axi4_0_ar_bits_burst,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_ar_bits_lock,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [3:0]  io_axi4_0_ar_bits_cache,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [2:0]  io_axi4_0_ar_bits_prot,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input  [3:0]  io_axi4_0_ar_bits_qos,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  input         io_axi4_0_r_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output        io_axi4_0_r_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output [3:0]  io_axi4_0_r_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output [63:0] io_axi4_0_r_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output [1:0]  io_axi4_0_r_bits_resp,	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
  output        io_axi4_0_r_bits_last	// @[generators/diplomacy/diplomacy/src/diplomacy/nodes/SourceNode.scala:76:21]
);

  wire        _axi4frag_auto_in_aw_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_in_w_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_in_b_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_in_b_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [1:0]  _axi4frag_auto_in_b_bits_resp;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_in_ar_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_in_r_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_in_r_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [63:0] _axi4frag_auto_in_r_bits_data;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [1:0]  _axi4frag_auto_in_r_bits_resp;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_in_r_bits_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_aw_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_out_aw_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [27:0] _axi4frag_auto_out_aw_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [2:0]  _axi4frag_auto_out_aw_bits_size;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [1:0]  _axi4frag_auto_out_aw_bits_burst;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_aw_bits_lock;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_out_aw_bits_cache;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [2:0]  _axi4frag_auto_out_aw_bits_prot;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_out_aw_bits_qos;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_aw_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_w_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [63:0] _axi4frag_auto_out_w_bits_data;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [7:0]  _axi4frag_auto_out_w_bits_strb;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_w_bits_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_b_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_ar_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_out_ar_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [27:0] _axi4frag_auto_out_ar_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [2:0]  _axi4frag_auto_out_ar_bits_size;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [1:0]  _axi4frag_auto_out_ar_bits_burst;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_ar_bits_lock;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_out_ar_bits_cache;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [2:0]  _axi4frag_auto_out_ar_bits_prot;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire [3:0]  _axi4frag_auto_out_ar_bits_qos;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_ar_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4frag_auto_out_r_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  wire        _axi4buf_auto_in_aw_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_w_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_b_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [3:0]  _axi4buf_auto_in_b_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [1:0]  _axi4buf_auto_in_b_bits_resp;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_b_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_ar_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_r_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [3:0]  _axi4buf_auto_in_r_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [63:0] _axi4buf_auto_in_r_bits_data;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [1:0]  _axi4buf_auto_in_r_bits_resp;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_r_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_in_r_bits_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_aw_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [3:0]  _axi4buf_auto_out_aw_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [27:0] _axi4buf_auto_out_aw_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_aw_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_w_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [63:0] _axi4buf_auto_out_w_bits_data;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [7:0]  _axi4buf_auto_out_w_bits_strb;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_b_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_ar_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [3:0]  _axi4buf_auto_out_ar_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire [27:0] _axi4buf_auto_out_ar_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_ar_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4buf_auto_out_r_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  wire        _axi4xbar_auto_anon_out_aw_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [3:0]  _axi4xbar_auto_anon_out_aw_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [27:0] _axi4xbar_auto_anon_out_aw_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [7:0]  _axi4xbar_auto_anon_out_aw_bits_len;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [2:0]  _axi4xbar_auto_anon_out_aw_bits_size;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [1:0]  _axi4xbar_auto_anon_out_aw_bits_burst;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_aw_bits_lock;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [3:0]  _axi4xbar_auto_anon_out_aw_bits_cache;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [2:0]  _axi4xbar_auto_anon_out_aw_bits_prot;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [3:0]  _axi4xbar_auto_anon_out_aw_bits_qos;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_w_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [63:0] _axi4xbar_auto_anon_out_w_bits_data;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [7:0]  _axi4xbar_auto_anon_out_w_bits_strb;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_w_bits_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_b_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_ar_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [3:0]  _axi4xbar_auto_anon_out_ar_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [27:0] _axi4xbar_auto_anon_out_ar_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [7:0]  _axi4xbar_auto_anon_out_ar_bits_len;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [2:0]  _axi4xbar_auto_anon_out_ar_bits_size;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [1:0]  _axi4xbar_auto_anon_out_ar_bits_burst;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_ar_bits_lock;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [3:0]  _axi4xbar_auto_anon_out_ar_bits_cache;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [2:0]  _axi4xbar_auto_anon_out_ar_bits_prot;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire [3:0]  _axi4xbar_auto_anon_out_ar_bits_qos;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _axi4xbar_auto_anon_out_r_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  wire        _srams_auto_in_aw_ready;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire        _srams_auto_in_w_ready;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire        _srams_auto_in_b_valid;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire [3:0]  _srams_auto_in_b_bits_id;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire        _srams_auto_in_b_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire        _srams_auto_in_ar_ready;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire        _srams_auto_in_r_valid;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire [3:0]  _srams_auto_in_r_bits_id;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire [63:0] _srams_auto_in_r_bits_data;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  wire        _srams_auto_in_r_bits_echo_real_last;	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  AXI4RAM srams (	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .clock                          (clock),
    .reset                          (reset),
    .auto_in_aw_ready               (_srams_auto_in_aw_ready),
    .auto_in_aw_valid               (_axi4buf_auto_out_aw_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_aw_bits_id             (_axi4buf_auto_out_aw_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_aw_bits_addr           (_axi4buf_auto_out_aw_bits_addr),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_aw_bits_echo_real_last (_axi4buf_auto_out_aw_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_w_ready                (_srams_auto_in_w_ready),
    .auto_in_w_valid                (_axi4buf_auto_out_w_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_w_bits_data            (_axi4buf_auto_out_w_bits_data),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_w_bits_strb            (_axi4buf_auto_out_w_bits_strb),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_b_ready                (_axi4buf_auto_out_b_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_b_valid                (_srams_auto_in_b_valid),
    .auto_in_b_bits_id              (_srams_auto_in_b_bits_id),
    .auto_in_b_bits_echo_real_last  (_srams_auto_in_b_bits_echo_real_last),
    .auto_in_ar_ready               (_srams_auto_in_ar_ready),
    .auto_in_ar_valid               (_axi4buf_auto_out_ar_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_ar_bits_id             (_axi4buf_auto_out_ar_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_ar_bits_addr           (_axi4buf_auto_out_ar_bits_addr),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_ar_bits_echo_real_last (_axi4buf_auto_out_ar_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_r_ready                (_axi4buf_auto_out_r_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_in_r_valid                (_srams_auto_in_r_valid),
    .auto_in_r_bits_id              (_srams_auto_in_r_bits_id),
    .auto_in_r_bits_data            (_srams_auto_in_r_bits_data),
    .auto_in_r_bits_echo_real_last  (_srams_auto_in_r_bits_echo_real_last)
  );	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  AXI4Xbar axi4xbar (	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .clock                       (clock),
    .reset                       (reset),
    .auto_anon_in_aw_ready       (io_axi4_0_aw_ready),
    .auto_anon_in_aw_valid       (io_axi4_0_aw_valid),
    .auto_anon_in_aw_bits_id     (io_axi4_0_aw_bits_id),
    .auto_anon_in_aw_bits_addr   (io_axi4_0_aw_bits_addr),
    .auto_anon_in_aw_bits_len    (io_axi4_0_aw_bits_len),
    .auto_anon_in_aw_bits_size   (io_axi4_0_aw_bits_size),
    .auto_anon_in_aw_bits_burst  (io_axi4_0_aw_bits_burst),
    .auto_anon_in_aw_bits_lock   (io_axi4_0_aw_bits_lock),
    .auto_anon_in_aw_bits_cache  (io_axi4_0_aw_bits_cache),
    .auto_anon_in_aw_bits_prot   (io_axi4_0_aw_bits_prot),
    .auto_anon_in_aw_bits_qos    (io_axi4_0_aw_bits_qos),
    .auto_anon_in_w_ready        (io_axi4_0_w_ready),
    .auto_anon_in_w_valid        (io_axi4_0_w_valid),
    .auto_anon_in_w_bits_data    (io_axi4_0_w_bits_data),
    .auto_anon_in_w_bits_strb    (io_axi4_0_w_bits_strb),
    .auto_anon_in_w_bits_last    (io_axi4_0_w_bits_last),
    .auto_anon_in_b_ready        (io_axi4_0_b_ready),
    .auto_anon_in_b_valid        (io_axi4_0_b_valid),
    .auto_anon_in_b_bits_id      (io_axi4_0_b_bits_id),
    .auto_anon_in_b_bits_resp    (io_axi4_0_b_bits_resp),
    .auto_anon_in_ar_ready       (io_axi4_0_ar_ready),
    .auto_anon_in_ar_valid       (io_axi4_0_ar_valid),
    .auto_anon_in_ar_bits_id     (io_axi4_0_ar_bits_id),
    .auto_anon_in_ar_bits_addr   (io_axi4_0_ar_bits_addr),
    .auto_anon_in_ar_bits_len    (io_axi4_0_ar_bits_len),
    .auto_anon_in_ar_bits_size   (io_axi4_0_ar_bits_size),
    .auto_anon_in_ar_bits_burst  (io_axi4_0_ar_bits_burst),
    .auto_anon_in_ar_bits_lock   (io_axi4_0_ar_bits_lock),
    .auto_anon_in_ar_bits_cache  (io_axi4_0_ar_bits_cache),
    .auto_anon_in_ar_bits_prot   (io_axi4_0_ar_bits_prot),
    .auto_anon_in_ar_bits_qos    (io_axi4_0_ar_bits_qos),
    .auto_anon_in_r_ready        (io_axi4_0_r_ready),
    .auto_anon_in_r_valid        (io_axi4_0_r_valid),
    .auto_anon_in_r_bits_id      (io_axi4_0_r_bits_id),
    .auto_anon_in_r_bits_data    (io_axi4_0_r_bits_data),
    .auto_anon_in_r_bits_resp    (io_axi4_0_r_bits_resp),
    .auto_anon_in_r_bits_last    (io_axi4_0_r_bits_last),
    .auto_anon_out_aw_ready      (_axi4frag_auto_in_aw_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_aw_valid      (_axi4xbar_auto_anon_out_aw_valid),
    .auto_anon_out_aw_bits_id    (_axi4xbar_auto_anon_out_aw_bits_id),
    .auto_anon_out_aw_bits_addr  (_axi4xbar_auto_anon_out_aw_bits_addr),
    .auto_anon_out_aw_bits_len   (_axi4xbar_auto_anon_out_aw_bits_len),
    .auto_anon_out_aw_bits_size  (_axi4xbar_auto_anon_out_aw_bits_size),
    .auto_anon_out_aw_bits_burst (_axi4xbar_auto_anon_out_aw_bits_burst),
    .auto_anon_out_aw_bits_lock  (_axi4xbar_auto_anon_out_aw_bits_lock),
    .auto_anon_out_aw_bits_cache (_axi4xbar_auto_anon_out_aw_bits_cache),
    .auto_anon_out_aw_bits_prot  (_axi4xbar_auto_anon_out_aw_bits_prot),
    .auto_anon_out_aw_bits_qos   (_axi4xbar_auto_anon_out_aw_bits_qos),
    .auto_anon_out_w_ready       (_axi4frag_auto_in_w_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_w_valid       (_axi4xbar_auto_anon_out_w_valid),
    .auto_anon_out_w_bits_data   (_axi4xbar_auto_anon_out_w_bits_data),
    .auto_anon_out_w_bits_strb   (_axi4xbar_auto_anon_out_w_bits_strb),
    .auto_anon_out_w_bits_last   (_axi4xbar_auto_anon_out_w_bits_last),
    .auto_anon_out_b_ready       (_axi4xbar_auto_anon_out_b_ready),
    .auto_anon_out_b_valid       (_axi4frag_auto_in_b_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_b_bits_id     (_axi4frag_auto_in_b_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_b_bits_resp   (_axi4frag_auto_in_b_bits_resp),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_ar_ready      (_axi4frag_auto_in_ar_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_ar_valid      (_axi4xbar_auto_anon_out_ar_valid),
    .auto_anon_out_ar_bits_id    (_axi4xbar_auto_anon_out_ar_bits_id),
    .auto_anon_out_ar_bits_addr  (_axi4xbar_auto_anon_out_ar_bits_addr),
    .auto_anon_out_ar_bits_len   (_axi4xbar_auto_anon_out_ar_bits_len),
    .auto_anon_out_ar_bits_size  (_axi4xbar_auto_anon_out_ar_bits_size),
    .auto_anon_out_ar_bits_burst (_axi4xbar_auto_anon_out_ar_bits_burst),
    .auto_anon_out_ar_bits_lock  (_axi4xbar_auto_anon_out_ar_bits_lock),
    .auto_anon_out_ar_bits_cache (_axi4xbar_auto_anon_out_ar_bits_cache),
    .auto_anon_out_ar_bits_prot  (_axi4xbar_auto_anon_out_ar_bits_prot),
    .auto_anon_out_ar_bits_qos   (_axi4xbar_auto_anon_out_ar_bits_qos),
    .auto_anon_out_r_ready       (_axi4xbar_auto_anon_out_r_ready),
    .auto_anon_out_r_valid       (_axi4frag_auto_in_r_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_r_bits_id     (_axi4frag_auto_in_r_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_r_bits_data   (_axi4frag_auto_in_r_bits_data),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_r_bits_resp   (_axi4frag_auto_in_r_bits_resp),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_anon_out_r_bits_last   (_axi4frag_auto_in_r_bits_last)	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
  );	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
  AXI4Buffer_1 axi4buf (	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .clock                           (clock),
    .reset                           (reset),
    .auto_in_aw_ready                (_axi4buf_auto_in_aw_ready),
    .auto_in_aw_valid                (_axi4frag_auto_out_aw_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_id              (_axi4frag_auto_out_aw_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_addr            (_axi4frag_auto_out_aw_bits_addr),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_size            (_axi4frag_auto_out_aw_bits_size),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_burst           (_axi4frag_auto_out_aw_bits_burst),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_lock            (_axi4frag_auto_out_aw_bits_lock),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_cache           (_axi4frag_auto_out_aw_bits_cache),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_prot            (_axi4frag_auto_out_aw_bits_prot),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_qos             (_axi4frag_auto_out_aw_bits_qos),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_aw_bits_echo_real_last  (_axi4frag_auto_out_aw_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_w_ready                 (_axi4buf_auto_in_w_ready),
    .auto_in_w_valid                 (_axi4frag_auto_out_w_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_w_bits_data             (_axi4frag_auto_out_w_bits_data),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_w_bits_strb             (_axi4frag_auto_out_w_bits_strb),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_w_bits_last             (_axi4frag_auto_out_w_bits_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_b_ready                 (_axi4frag_auto_out_b_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_b_valid                 (_axi4buf_auto_in_b_valid),
    .auto_in_b_bits_id               (_axi4buf_auto_in_b_bits_id),
    .auto_in_b_bits_resp             (_axi4buf_auto_in_b_bits_resp),
    .auto_in_b_bits_echo_real_last   (_axi4buf_auto_in_b_bits_echo_real_last),
    .auto_in_ar_ready                (_axi4buf_auto_in_ar_ready),
    .auto_in_ar_valid                (_axi4frag_auto_out_ar_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_id              (_axi4frag_auto_out_ar_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_addr            (_axi4frag_auto_out_ar_bits_addr),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_size            (_axi4frag_auto_out_ar_bits_size),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_burst           (_axi4frag_auto_out_ar_bits_burst),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_lock            (_axi4frag_auto_out_ar_bits_lock),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_cache           (_axi4frag_auto_out_ar_bits_cache),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_prot            (_axi4frag_auto_out_ar_bits_prot),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_qos             (_axi4frag_auto_out_ar_bits_qos),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_ar_bits_echo_real_last  (_axi4frag_auto_out_ar_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_r_ready                 (_axi4frag_auto_out_r_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .auto_in_r_valid                 (_axi4buf_auto_in_r_valid),
    .auto_in_r_bits_id               (_axi4buf_auto_in_r_bits_id),
    .auto_in_r_bits_data             (_axi4buf_auto_in_r_bits_data),
    .auto_in_r_bits_resp             (_axi4buf_auto_in_r_bits_resp),
    .auto_in_r_bits_echo_real_last   (_axi4buf_auto_in_r_bits_echo_real_last),
    .auto_in_r_bits_last             (_axi4buf_auto_in_r_bits_last),
    .auto_out_aw_ready               (_srams_auto_in_aw_ready),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_aw_valid               (_axi4buf_auto_out_aw_valid),
    .auto_out_aw_bits_id             (_axi4buf_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr           (_axi4buf_auto_out_aw_bits_addr),
    .auto_out_aw_bits_echo_real_last (_axi4buf_auto_out_aw_bits_echo_real_last),
    .auto_out_w_ready                (_srams_auto_in_w_ready),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_w_valid                (_axi4buf_auto_out_w_valid),
    .auto_out_w_bits_data            (_axi4buf_auto_out_w_bits_data),
    .auto_out_w_bits_strb            (_axi4buf_auto_out_w_bits_strb),
    .auto_out_b_ready                (_axi4buf_auto_out_b_ready),
    .auto_out_b_valid                (_srams_auto_in_b_valid),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_b_bits_id              (_srams_auto_in_b_bits_id),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_b_bits_echo_real_last  (_srams_auto_in_b_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_ar_ready               (_srams_auto_in_ar_ready),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_ar_valid               (_axi4buf_auto_out_ar_valid),
    .auto_out_ar_bits_id             (_axi4buf_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr           (_axi4buf_auto_out_ar_bits_addr),
    .auto_out_ar_bits_echo_real_last (_axi4buf_auto_out_ar_bits_echo_real_last),
    .auto_out_r_ready                (_axi4buf_auto_out_r_ready),
    .auto_out_r_valid                (_srams_auto_in_r_valid),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_r_bits_id              (_srams_auto_in_r_bits_id),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_r_bits_data            (_srams_auto_in_r_bits_data),	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
    .auto_out_r_bits_echo_real_last  (_srams_auto_in_r_bits_echo_real_last)	// @[generators/rocket-chip/src/main/scala/system/SimAXIMem.scala:22:15]
  );	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  AXI4Fragmenter axi4frag (	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
    .clock                           (clock),
    .reset                           (reset),
    .auto_in_aw_ready                (_axi4frag_auto_in_aw_ready),
    .auto_in_aw_valid                (_axi4xbar_auto_anon_out_aw_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_id              (_axi4xbar_auto_anon_out_aw_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_addr            (_axi4xbar_auto_anon_out_aw_bits_addr),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_len             (_axi4xbar_auto_anon_out_aw_bits_len),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_size            (_axi4xbar_auto_anon_out_aw_bits_size),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_burst           (_axi4xbar_auto_anon_out_aw_bits_burst),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_lock            (_axi4xbar_auto_anon_out_aw_bits_lock),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_cache           (_axi4xbar_auto_anon_out_aw_bits_cache),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_prot            (_axi4xbar_auto_anon_out_aw_bits_prot),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_aw_bits_qos             (_axi4xbar_auto_anon_out_aw_bits_qos),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_w_ready                 (_axi4frag_auto_in_w_ready),
    .auto_in_w_valid                 (_axi4xbar_auto_anon_out_w_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_w_bits_data             (_axi4xbar_auto_anon_out_w_bits_data),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_w_bits_strb             (_axi4xbar_auto_anon_out_w_bits_strb),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_w_bits_last             (_axi4xbar_auto_anon_out_w_bits_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_b_ready                 (_axi4xbar_auto_anon_out_b_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_b_valid                 (_axi4frag_auto_in_b_valid),
    .auto_in_b_bits_id               (_axi4frag_auto_in_b_bits_id),
    .auto_in_b_bits_resp             (_axi4frag_auto_in_b_bits_resp),
    .auto_in_ar_ready                (_axi4frag_auto_in_ar_ready),
    .auto_in_ar_valid                (_axi4xbar_auto_anon_out_ar_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_id              (_axi4xbar_auto_anon_out_ar_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_addr            (_axi4xbar_auto_anon_out_ar_bits_addr),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_len             (_axi4xbar_auto_anon_out_ar_bits_len),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_size            (_axi4xbar_auto_anon_out_ar_bits_size),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_burst           (_axi4xbar_auto_anon_out_ar_bits_burst),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_lock            (_axi4xbar_auto_anon_out_ar_bits_lock),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_cache           (_axi4xbar_auto_anon_out_ar_bits_cache),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_prot            (_axi4xbar_auto_anon_out_ar_bits_prot),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_ar_bits_qos             (_axi4xbar_auto_anon_out_ar_bits_qos),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_r_ready                 (_axi4xbar_auto_anon_out_r_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Xbar.scala:241:30]
    .auto_in_r_valid                 (_axi4frag_auto_in_r_valid),
    .auto_in_r_bits_id               (_axi4frag_auto_in_r_bits_id),
    .auto_in_r_bits_data             (_axi4frag_auto_in_r_bits_data),
    .auto_in_r_bits_resp             (_axi4frag_auto_in_r_bits_resp),
    .auto_in_r_bits_last             (_axi4frag_auto_in_r_bits_last),
    .auto_out_aw_ready               (_axi4buf_auto_in_aw_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_aw_valid               (_axi4frag_auto_out_aw_valid),
    .auto_out_aw_bits_id             (_axi4frag_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr           (_axi4frag_auto_out_aw_bits_addr),
    .auto_out_aw_bits_size           (_axi4frag_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst          (_axi4frag_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock           (_axi4frag_auto_out_aw_bits_lock),
    .auto_out_aw_bits_cache          (_axi4frag_auto_out_aw_bits_cache),
    .auto_out_aw_bits_prot           (_axi4frag_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos            (_axi4frag_auto_out_aw_bits_qos),
    .auto_out_aw_bits_echo_real_last (_axi4frag_auto_out_aw_bits_echo_real_last),
    .auto_out_w_ready                (_axi4buf_auto_in_w_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_w_valid                (_axi4frag_auto_out_w_valid),
    .auto_out_w_bits_data            (_axi4frag_auto_out_w_bits_data),
    .auto_out_w_bits_strb            (_axi4frag_auto_out_w_bits_strb),
    .auto_out_w_bits_last            (_axi4frag_auto_out_w_bits_last),
    .auto_out_b_ready                (_axi4frag_auto_out_b_ready),
    .auto_out_b_valid                (_axi4buf_auto_in_b_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_b_bits_id              (_axi4buf_auto_in_b_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_b_bits_resp            (_axi4buf_auto_in_b_bits_resp),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_b_bits_echo_real_last  (_axi4buf_auto_in_b_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_ar_ready               (_axi4buf_auto_in_ar_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_ar_valid               (_axi4frag_auto_out_ar_valid),
    .auto_out_ar_bits_id             (_axi4frag_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr           (_axi4frag_auto_out_ar_bits_addr),
    .auto_out_ar_bits_size           (_axi4frag_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst          (_axi4frag_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock           (_axi4frag_auto_out_ar_bits_lock),
    .auto_out_ar_bits_cache          (_axi4frag_auto_out_ar_bits_cache),
    .auto_out_ar_bits_prot           (_axi4frag_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos            (_axi4frag_auto_out_ar_bits_qos),
    .auto_out_ar_bits_echo_real_last (_axi4frag_auto_out_ar_bits_echo_real_last),
    .auto_out_r_ready                (_axi4frag_auto_out_r_ready),
    .auto_out_r_valid                (_axi4buf_auto_in_r_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_r_bits_id              (_axi4buf_auto_in_r_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_r_bits_data            (_axi4buf_auto_in_r_bits_data),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_r_bits_resp            (_axi4buf_auto_in_r_bits_resp),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_r_bits_echo_real_last  (_axi4buf_auto_in_r_bits_echo_real_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
    .auto_out_r_bits_last            (_axi4buf_auto_in_r_bits_last)	// @[generators/rocket-chip/src/main/scala/amba/axi4/Buffer.scala:68:29]
  );	// @[generators/rocket-chip/src/main/scala/amba/axi4/Fragmenter.scala:224:30]
endmodule

