// Generated by CIRCT firtool-1.75.0
module TestHarness(	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
  input  clock,	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
  input  reset,	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
  output io_success	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:20:14]
);

  wire        _source_1_clk;	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  wire        _source_clk;	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  wire        _harnessBinderReset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _simdram_axi_aw_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_w_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_b_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [3:0]  _simdram_axi_b_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [1:0]  _simdram_axi_b_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_ar_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_r_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [3:0]  _simdram_axi_r_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [63:0] _simdram_axi_r_bits_data;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire [1:0]  _simdram_axi_r_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _simdram_axi_r_bits_last;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  wire        _mmio_mem_io_axi4_0_aw_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_w_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_b_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [3:0]  _mmio_mem_io_axi4_0_b_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [1:0]  _mmio_mem_io_axi4_0_b_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_ar_ready;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_r_valid;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [3:0]  _mmio_mem_io_axi4_0_r_bits_id;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [63:0] _mmio_mem_io_axi4_0_r_bits_data;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire [1:0]  _mmio_mem_io_axi4_0_r_bits_resp;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _mmio_mem_io_axi4_0_r_bits_last;	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  wire        _chiptop0_axi4_mmio_0_clock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_aw_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [29:0] _chiptop0_axi4_mmio_0_bits_aw_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_aw_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_aw_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_w_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [63:0] _chiptop0_axi4_mmio_0_bits_w_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mmio_0_bits_w_bits_strb;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_w_bits_last;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_b_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_ar_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [29:0] _chiptop0_axi4_mmio_0_bits_ar_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_ar_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mmio_0_bits_ar_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mmio_0_bits_r_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_clock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_aw_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_aw_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_aw_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_aw_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mem_0_bits_aw_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_aw_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_aw_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_aw_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_w_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [63:0] _chiptop0_axi4_mem_0_bits_w_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_w_bits_strb;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_w_bits_last;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_b_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_ar_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_id;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_axi4_mem_0_bits_ar_bits_addr;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_axi4_mem_0_bits_ar_bits_len;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_ar_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [1:0]  _chiptop0_axi4_mem_0_bits_ar_bits_burst;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_ar_bits_lock;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_cache;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_axi4_mem_0_bits_ar_bits_prot;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_axi4_mem_0_bits_ar_bits_qos;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_axi4_mem_0_bits_r_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi4_mmio_0_clock              (_chiptop0_axi4_mmio_0_clock),
    .axi4_mmio_0_bits_aw_ready      (_mmio_mem_io_axi4_0_aw_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_aw_valid      (_chiptop0_axi4_mmio_0_bits_aw_valid),
    .axi4_mmio_0_bits_aw_bits_id    (_chiptop0_axi4_mmio_0_bits_aw_bits_id),
    .axi4_mmio_0_bits_aw_bits_addr  (_chiptop0_axi4_mmio_0_bits_aw_bits_addr),
    .axi4_mmio_0_bits_aw_bits_len   (_chiptop0_axi4_mmio_0_bits_aw_bits_len),
    .axi4_mmio_0_bits_aw_bits_size  (_chiptop0_axi4_mmio_0_bits_aw_bits_size),
    .axi4_mmio_0_bits_aw_bits_burst (_chiptop0_axi4_mmio_0_bits_aw_bits_burst),
    .axi4_mmio_0_bits_aw_bits_lock  (_chiptop0_axi4_mmio_0_bits_aw_bits_lock),
    .axi4_mmio_0_bits_aw_bits_cache (_chiptop0_axi4_mmio_0_bits_aw_bits_cache),
    .axi4_mmio_0_bits_aw_bits_prot  (_chiptop0_axi4_mmio_0_bits_aw_bits_prot),
    .axi4_mmio_0_bits_aw_bits_qos   (_chiptop0_axi4_mmio_0_bits_aw_bits_qos),
    .axi4_mmio_0_bits_w_ready       (_mmio_mem_io_axi4_0_w_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_w_valid       (_chiptop0_axi4_mmio_0_bits_w_valid),
    .axi4_mmio_0_bits_w_bits_data   (_chiptop0_axi4_mmio_0_bits_w_bits_data),
    .axi4_mmio_0_bits_w_bits_strb   (_chiptop0_axi4_mmio_0_bits_w_bits_strb),
    .axi4_mmio_0_bits_w_bits_last   (_chiptop0_axi4_mmio_0_bits_w_bits_last),
    .axi4_mmio_0_bits_b_ready       (_chiptop0_axi4_mmio_0_bits_b_ready),
    .axi4_mmio_0_bits_b_valid       (_mmio_mem_io_axi4_0_b_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_b_bits_id     (_mmio_mem_io_axi4_0_b_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_b_bits_resp   (_mmio_mem_io_axi4_0_b_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_ar_ready      (_mmio_mem_io_axi4_0_ar_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_ar_valid      (_chiptop0_axi4_mmio_0_bits_ar_valid),
    .axi4_mmio_0_bits_ar_bits_id    (_chiptop0_axi4_mmio_0_bits_ar_bits_id),
    .axi4_mmio_0_bits_ar_bits_addr  (_chiptop0_axi4_mmio_0_bits_ar_bits_addr),
    .axi4_mmio_0_bits_ar_bits_len   (_chiptop0_axi4_mmio_0_bits_ar_bits_len),
    .axi4_mmio_0_bits_ar_bits_size  (_chiptop0_axi4_mmio_0_bits_ar_bits_size),
    .axi4_mmio_0_bits_ar_bits_burst (_chiptop0_axi4_mmio_0_bits_ar_bits_burst),
    .axi4_mmio_0_bits_ar_bits_lock  (_chiptop0_axi4_mmio_0_bits_ar_bits_lock),
    .axi4_mmio_0_bits_ar_bits_cache (_chiptop0_axi4_mmio_0_bits_ar_bits_cache),
    .axi4_mmio_0_bits_ar_bits_prot  (_chiptop0_axi4_mmio_0_bits_ar_bits_prot),
    .axi4_mmio_0_bits_ar_bits_qos   (_chiptop0_axi4_mmio_0_bits_ar_bits_qos),
    .axi4_mmio_0_bits_r_ready       (_chiptop0_axi4_mmio_0_bits_r_ready),
    .axi4_mmio_0_bits_r_valid       (_mmio_mem_io_axi4_0_r_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_id     (_mmio_mem_io_axi4_0_r_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_data   (_mmio_mem_io_axi4_0_r_bits_data),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_resp   (_mmio_mem_io_axi4_0_r_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mmio_0_bits_r_bits_last   (_mmio_mem_io_axi4_0_r_bits_last),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .axi4_mem_0_clock               (_chiptop0_axi4_mem_0_clock),
    .axi4_mem_0_bits_aw_ready       (_simdram_axi_aw_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_aw_valid       (_chiptop0_axi4_mem_0_bits_aw_valid),
    .axi4_mem_0_bits_aw_bits_id     (_chiptop0_axi4_mem_0_bits_aw_bits_id),
    .axi4_mem_0_bits_aw_bits_addr   (_chiptop0_axi4_mem_0_bits_aw_bits_addr),
    .axi4_mem_0_bits_aw_bits_len    (_chiptop0_axi4_mem_0_bits_aw_bits_len),
    .axi4_mem_0_bits_aw_bits_size   (_chiptop0_axi4_mem_0_bits_aw_bits_size),
    .axi4_mem_0_bits_aw_bits_burst  (_chiptop0_axi4_mem_0_bits_aw_bits_burst),
    .axi4_mem_0_bits_aw_bits_lock   (_chiptop0_axi4_mem_0_bits_aw_bits_lock),
    .axi4_mem_0_bits_aw_bits_cache  (_chiptop0_axi4_mem_0_bits_aw_bits_cache),
    .axi4_mem_0_bits_aw_bits_prot   (_chiptop0_axi4_mem_0_bits_aw_bits_prot),
    .axi4_mem_0_bits_aw_bits_qos    (_chiptop0_axi4_mem_0_bits_aw_bits_qos),
    .axi4_mem_0_bits_w_ready        (_simdram_axi_w_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_w_valid        (_chiptop0_axi4_mem_0_bits_w_valid),
    .axi4_mem_0_bits_w_bits_data    (_chiptop0_axi4_mem_0_bits_w_bits_data),
    .axi4_mem_0_bits_w_bits_strb    (_chiptop0_axi4_mem_0_bits_w_bits_strb),
    .axi4_mem_0_bits_w_bits_last    (_chiptop0_axi4_mem_0_bits_w_bits_last),
    .axi4_mem_0_bits_b_ready        (_chiptop0_axi4_mem_0_bits_b_ready),
    .axi4_mem_0_bits_b_valid        (_simdram_axi_b_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_b_bits_id      (_simdram_axi_b_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_b_bits_resp    (_simdram_axi_b_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_ar_ready       (_simdram_axi_ar_ready),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_ar_valid       (_chiptop0_axi4_mem_0_bits_ar_valid),
    .axi4_mem_0_bits_ar_bits_id     (_chiptop0_axi4_mem_0_bits_ar_bits_id),
    .axi4_mem_0_bits_ar_bits_addr   (_chiptop0_axi4_mem_0_bits_ar_bits_addr),
    .axi4_mem_0_bits_ar_bits_len    (_chiptop0_axi4_mem_0_bits_ar_bits_len),
    .axi4_mem_0_bits_ar_bits_size   (_chiptop0_axi4_mem_0_bits_ar_bits_size),
    .axi4_mem_0_bits_ar_bits_burst  (_chiptop0_axi4_mem_0_bits_ar_bits_burst),
    .axi4_mem_0_bits_ar_bits_lock   (_chiptop0_axi4_mem_0_bits_ar_bits_lock),
    .axi4_mem_0_bits_ar_bits_cache  (_chiptop0_axi4_mem_0_bits_ar_bits_cache),
    .axi4_mem_0_bits_ar_bits_prot   (_chiptop0_axi4_mem_0_bits_ar_bits_prot),
    .axi4_mem_0_bits_ar_bits_qos    (_chiptop0_axi4_mem_0_bits_ar_bits_qos),
    .axi4_mem_0_bits_r_ready        (_chiptop0_axi4_mem_0_bits_r_ready),
    .axi4_mem_0_bits_r_valid        (_simdram_axi_r_valid),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_id      (_simdram_axi_r_bits_id),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_data    (_simdram_axi_r_bits_data),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_resp    (_simdram_axi_r_bits_resp),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .axi4_mem_0_bits_r_bits_last    (_simdram_axi_r_bits_last),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .custom_boot                    (_plusarg_reader_out),	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .reset_io                       (reset),
    .clock_uncore                   (_source_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .clock_tap                      (/* unused */)
  );	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  SimAXIMem mmio_mem (	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
    .clock                   (_chiptop0_axi4_mmio_0_clock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .reset                   (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_axi4_0_aw_ready      (_mmio_mem_io_axi4_0_aw_ready),
    .io_axi4_0_aw_valid      (_chiptop0_axi4_mmio_0_bits_aw_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_id    (_chiptop0_axi4_mmio_0_bits_aw_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_addr  (_chiptop0_axi4_mmio_0_bits_aw_bits_addr[28:0]),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:159:27, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_len   (_chiptop0_axi4_mmio_0_bits_aw_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_size  (_chiptop0_axi4_mmio_0_bits_aw_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_burst (_chiptop0_axi4_mmio_0_bits_aw_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_lock  (_chiptop0_axi4_mmio_0_bits_aw_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_cache (_chiptop0_axi4_mmio_0_bits_aw_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_prot  (_chiptop0_axi4_mmio_0_bits_aw_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_aw_bits_qos   (_chiptop0_axi4_mmio_0_bits_aw_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_ready       (_mmio_mem_io_axi4_0_w_ready),
    .io_axi4_0_w_valid       (_chiptop0_axi4_mmio_0_bits_w_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_bits_data   (_chiptop0_axi4_mmio_0_bits_w_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_bits_strb   (_chiptop0_axi4_mmio_0_bits_w_bits_strb),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_w_bits_last   (_chiptop0_axi4_mmio_0_bits_w_bits_last),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_b_ready       (_chiptop0_axi4_mmio_0_bits_b_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_b_valid       (_mmio_mem_io_axi4_0_b_valid),
    .io_axi4_0_b_bits_id     (_mmio_mem_io_axi4_0_b_bits_id),
    .io_axi4_0_b_bits_resp   (_mmio_mem_io_axi4_0_b_bits_resp),
    .io_axi4_0_ar_ready      (_mmio_mem_io_axi4_0_ar_ready),
    .io_axi4_0_ar_valid      (_chiptop0_axi4_mmio_0_bits_ar_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_id    (_chiptop0_axi4_mmio_0_bits_ar_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_addr  (_chiptop0_axi4_mmio_0_bits_ar_bits_addr[28:0]),	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:159:27, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_len   (_chiptop0_axi4_mmio_0_bits_ar_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_size  (_chiptop0_axi4_mmio_0_bits_ar_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_burst (_chiptop0_axi4_mmio_0_bits_ar_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_lock  (_chiptop0_axi4_mmio_0_bits_ar_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_cache (_chiptop0_axi4_mmio_0_bits_ar_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_prot  (_chiptop0_axi4_mmio_0_bits_ar_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_ar_bits_qos   (_chiptop0_axi4_mmio_0_bits_ar_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_r_ready       (_chiptop0_axi4_mmio_0_bits_r_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .io_axi4_0_r_valid       (_mmio_mem_io_axi4_0_r_valid),
    .io_axi4_0_r_bits_id     (_mmio_mem_io_axi4_0_r_bits_id),
    .io_axi4_0_r_bits_data   (_mmio_mem_io_axi4_0_r_bits_data),
    .io_axi4_0_r_bits_resp   (_mmio_mem_io_axi4_0_r_bits_resp),
    .io_axi4_0_r_bits_last   (_mmio_mem_io_axi4_0_r_bits_last)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:158:38]
  SimDRAM #(
    .ADDR_BITS(32),
    .CHIP_ID(0),
    .CLOCK_HZ(500000000),
    .DATA_BITS(64),
    .ID_BITS(4),
    .LINE_SIZE(64),
    .MEM_BASE(40'd2147483648),
    .MEM_SIZE(268435456)
  ) simdram (	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
    .clock             (_chiptop0_axi4_mem_0_clock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .reset             (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .axi_aw_ready      (_simdram_axi_aw_ready),
    .axi_aw_valid      (_chiptop0_axi4_mem_0_bits_aw_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_id    (_chiptop0_axi4_mem_0_bits_aw_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_addr  (_chiptop0_axi4_mem_0_bits_aw_bits_addr),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_len   (_chiptop0_axi4_mem_0_bits_aw_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_size  (_chiptop0_axi4_mem_0_bits_aw_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_burst (_chiptop0_axi4_mem_0_bits_aw_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_lock  (_chiptop0_axi4_mem_0_bits_aw_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_cache (_chiptop0_axi4_mem_0_bits_aw_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_prot  (_chiptop0_axi4_mem_0_bits_aw_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_aw_bits_qos   (_chiptop0_axi4_mem_0_bits_aw_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_ready       (_simdram_axi_w_ready),
    .axi_w_valid       (_chiptop0_axi4_mem_0_bits_w_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_bits_data   (_chiptop0_axi4_mem_0_bits_w_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_bits_strb   (_chiptop0_axi4_mem_0_bits_w_bits_strb),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_w_bits_last   (_chiptop0_axi4_mem_0_bits_w_bits_last),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_b_ready       (_chiptop0_axi4_mem_0_bits_b_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_b_valid       (_simdram_axi_b_valid),
    .axi_b_bits_id     (_simdram_axi_b_bits_id),
    .axi_b_bits_resp   (_simdram_axi_b_bits_resp),
    .axi_ar_ready      (_simdram_axi_ar_ready),
    .axi_ar_valid      (_chiptop0_axi4_mem_0_bits_ar_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_id    (_chiptop0_axi4_mem_0_bits_ar_bits_id),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_addr  (_chiptop0_axi4_mem_0_bits_ar_bits_addr),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_len   (_chiptop0_axi4_mem_0_bits_ar_bits_len),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_size  (_chiptop0_axi4_mem_0_bits_ar_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_burst (_chiptop0_axi4_mem_0_bits_ar_bits_burst),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_lock  (_chiptop0_axi4_mem_0_bits_ar_bits_lock),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_cache (_chiptop0_axi4_mem_0_bits_ar_bits_cache),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_prot  (_chiptop0_axi4_mem_0_bits_ar_bits_prot),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_ar_bits_qos   (_chiptop0_axi4_mem_0_bits_ar_bits_qos),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_r_ready       (_chiptop0_axi4_mem_0_bits_r_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .axi_r_valid       (_simdram_axi_r_valid),
    .axi_r_bits_id     (_simdram_axi_r_bits_id),
    .axi_r_bits_data   (_simdram_axi_r_bits_data),
    .axi_r_bits_resp   (_simdram_axi_r_bits_resp),
    .axi_r_bits_last   (_simdram_axi_r_bits_last)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessBinders.scala:129:21]
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("custom_boot_pin=%d"),
    .WIDTH(1)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  ResetCatchAndSync_d3 harnessBinderReset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_source_1_clk),	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .reset         (reset),
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  ClockSourceAtFreqMHz #(
    .PERIOD(2.000000e+00)
  ) source (	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .power (1'h1),
    .gate  (1'h0),
    .clk   (_source_clk)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  ClockSourceAtFreqMHz #(
    .PERIOD(1.000000e+01)
  ) source_1 (	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
    .power (1'h1),
    .gate  (1'h0),
    .clk   (_source_1_clk)
  );	// @[generators/chipyard/src/main/scala/harness/HarnessClocks.scala:70:26]
  assign io_success = 1'h0;	// @[generators/chipyard/src/main/scala/harness/TestHarness.scala:19:7]
endmodule

