# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.runs/synth_1/BD_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param bd.open.in_stealth_mode 2
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu3eg-sbva484-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.cache/wt [current_project]
set_property parent.project_path /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part avnet-tria:ultra96v2:part0:1.3 [current_project]
set_property ip_output_repo /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/hdl/BD_wrapper.v
add_files /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.srcs/sources_1/bd/BD/BD.bd
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_zynq_ultra_ps_e_0_0/BD_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_zynq_ultra_ps_e_0_0/BD_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_gpio_0_0/BD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_gpio_1_0/BD_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_gpio_1_0/BD_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_gpio_1_0/BD_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_1/bd_5c0d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_2/bd_5c0d_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_3/bd_5c0d_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_4/bd_5c0d_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_5/bd_5c0d_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_6/bd_5c0d_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_7/bd_5c0d_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_8/bd_5c0d_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_9/bd_5c0d_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_10/bd_5c0d_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_11/bd_5c0d_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_12/bd_5c0d_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_13/bd_5c0d_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_14/bd_5c0d_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_15/bd_5c0d_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_16/bd_5c0d_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_20/bd_5c0d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_21/bd_5c0d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_22/bd_5c0d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_23/bd_5c0d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_24/bd_5c0d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_25/bd_5c0d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_29/bd_5c0d_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_30/bd_5c0d_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_31/bd_5c0d_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_32/bd_5c0d_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_33/bd_5c0d_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_34/bd_5c0d_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_35/bd_5c0d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_36/bd_5c0d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_37/bd_5c0d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_38/bd_5c0d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_39/bd_5c0d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_40/bd_5c0d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_42/bd_5c0d_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_43/bd_5c0d_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_44/bd_5c0d_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_45/bd_5c0d_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_46/bd_5c0d_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/bd_0/ip/ip_47/bd_5c0d_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_rst_ps8_0_100M_0/BD_rst_ps8_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_rst_ps8_0_100M_0/BD_rst_ps8_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_rst_ps8_0_100M_0/BD_rst_ps8_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_1/bd_4797_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_1/bd_4797_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_2/bd_4797_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_2/bd_4797_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_3/bd_4797_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_3/bd_4797_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_4/bd_4797_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_5/bd_4797_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_6/bd_4797_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_7/bd_4797_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_8/bd_4797_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_12/bd_4797_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_13/bd_4797_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_14/bd_4797_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_15/bd_4797_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_16/bd_4797_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_17/bd_4797_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_21/bd_4797_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_22/bd_4797_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_23/bd_4797_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_24/bd_4797_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_25/bd_4797_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_26/bd_4797_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_27/bd_4797_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_28/bd_4797_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_29/bd_4797_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_30/bd_4797_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_31/bd_4797_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/bd_0/ip/ip_32/bd_4797_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/ip/BD_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.gen/sources_1/bd/BD/BD_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /mnt/Storage/SCHOOL/Capstone/bringup/ChaosCore-FPGA/ChaosCoreFPGAConfig/ChaosCore/ChaosCore.srcs/utils_1/imports/synth_1/BD_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top BD_wrapper -part xczu3eg-sbva484-1-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BD_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file BD_wrapper_utilization_synth.rpt -pb BD_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
